### ISSUE TITLE
params accepts map, but not a tuple

### ISSUE THREAD

**Issue by sudomilk** [edgurgel/httpoison#102]
Line 136 of `httpoison/lib/httpoison/base.ex` has the following description:

```
        * `:params` - an enumerable consisting of two-item tuples that will be appended to the url as query string parameters

```

But, and maybe I'm just doing it incorrectly, I can only seem to get this to work with a map like so:

```
#within a module
  HTTPoison.get!(@lci_url <> "/visitors", @headers, [params: %{"state" => "chatting"}])
```

If I try with a two item tuple like `[params: {"state", "chatting"}]`, I receive the following error:

```
** (Protocol.UndefinedError) protocol Enumerable not implemented for {"state", "chatting"}
       (elixir) lib/enum.ex:1: Enumerable.impl_for!/1
       (elixir) lib/enum.ex:112: Enumerable.reduce/3
       (elixir) lib/enum.ex:1274: Enum.reduce/3
       (elixir) lib/enum.ex:1007: Enum.map_join/3
    (httpoison) lib/httpoison.ex:66: HTTPoison.request/5
    (httpoison) lib/httpoison.ex:66: HTTPoison.request!/5
```

Am I just not passing a two-item tuple properly, or is this supposed to accept a Map instead?

**Comment by edgurgel** [comment]
The list of tuples would `params: [{"state", "chatting"}]`. Can you try these?

**Comment by sudomilk** [comment]
`params: [{"state", "chatting"}]` works perfectly; thank you!
