### ISSUE TITLE
Sanity of asynchronous response handling

### ISSUE THREAD

**Issue by Rattenkrieg** [edgurgel/httpoison#108]
I'm trying to extend functionality of processing GET request illustrated in `Dave Thomas's "Programming Elixir"` book towards parallel asynchronous processing of multiple requests. HTTPoison capabilities for such a task seems too low-level for me.
Here is original code:
```elixir
def fetch(user, project) do
  issues_url(user, project)
  |> HTTPoison.get(@user_agent)
  |> handle_response
end
```
It sends GET request, blocks (as far as I understand) process till response come in and somehow handles it.
Next I adapt it to be parallel async firehose:
```elixir
items
|> Enum.map(HTTPoison.get(@user_agent, [stream_to: self]))
|> Enum.map(fn {:ok, %HTTPoison.AsyncResponse{id: id}} ->
  collect_response(id, self, <<>>)
end)

def collect_response(id, par, data) do
  receive do
    %HTTPoison.AsyncStatus{id: ^id, code: 200} ->
      collect_response(id, par, data)
    %HTTPoison.AsyncHeaders{id: ^id, headers: headers} ->
      collect_response(id, par, data)
    %HTTPoison.AsyncChunk{id: ^id, chunk: chunk} ->
      collect_response(id, par, data <> chunk)
    %HTTPoison.AsyncEnd{id: ^id} ->
      send par, handle_response({:ok, %{status_code: 200, body: data}})
  end
end
```
This `collect_response` routine looks too boilerplate-ish for me. 
1. Is there more terse way to achieve such task?
2. Have I did it Elixir-way? / Should I bother to keep all that stuff parallel-async or it's ok to simply -
```elixir
items |> Enum.map(HTTPoison.get(@user_agent) |> handle_response)
```

**Comment by edgurgel** [comment]
You can separate processes to handle the request synchronously or use the async as you did. It seems too much to write but the request is split into these parts and you need to "merge" them as you like. I would prefer to use [`Task`](http://elixir-lang.org/docs/v1.0/elixir/Task.html) and run the actual request synchronously unless you need to use the chunks of the body in some different way.

**Comment by Rattenkrieg** [comment]
Do you assuming something like 
```elixir
items 
|> Enum.map(&Task.async(fn -> HTTPoison.get(&1, @user_agent)  end)
|> Enum.map(&Task.await(&1, 10000)
|> Enum.map(&handle_response/1)
```
advising to use Task?
I referring to my C# background, where doing somewhat similar to code above using `System.Threading.Tasks.Task` may led to occupation up to `count(items)` of CLR threads.
Consider this snippet:
```csharp
var client = new WebClient();
Action<Task<string>> handleTaskResponse = t => Console.WriteLine(t.Result);
var items = new List<Uri>();
items
.Select(i => Task.Factory.StartNew(() => client.DownloadString(i))) // since DownloadString is blocking operation, CLR thread assigned to this particular task will not be able to execute any code untill DownloadString returns
.Select(t => t.ContinueWith(handleTaskResponse)); // asynchronous continuation with callback
```
Even since processing will appear completely asynchronous to user, it will stress thread pool by acquiring many threads which will stand idle after sending GET request and before it completes.
To overcome such ineffectiveness almost each IO method in .NET comes paired with its asynchronous companion, which leverages underlying system IO routines in asynchronous fashion.
So if we change first Select call to
```csharp
.Select(i => client.DownloadStringTaskAsync(i))
```
semantically similar to
```elixir
|> Enum.map(HTTPoison.get(@user_agent, [stream_to: self]))
```
it will bother thread pool's thread only to schedule IO job to OS HTTP module, and one more time when response come back to dispatch it back to the caller. All the time in between scheduling and dispatching thread will be on duty. So whole this batch procedure potentially can be handled by one thread pool's thread solely. However it's a lot less verbose to dispatch task's result in C# - http response returns as one descreet entity.

I hope, now you can see what bothers me with `Task` approach in Elixir. Will there be difference in runtime resources consumption for, say 100 simultaneous http requests?

**Comment by edgurgel** [comment]
* Erlang/Elixir processes do not match 1-1 with System Threads. This presentation explains really well how processes run on top of the VM: https://www.youtube.com/watch?v=_Pwlvy3zz9M
* HTTPoison has a limit of open connections per pool. More here: https://github.com/edgurgel/httpoison/issues/73
* You can always use some pool of processes to load balance your requests: 
  * https://github.com/devinus/poolboy
  * https://github.com/PSPDFKit-labs/sidetask
  * ETC

**Comment by Rattenkrieg** [comment]
@edgurgel many thanks for provided video and useful links. Things seems much clearer now.

**Comment by edgurgel** [comment]
Great! :+1:
