### ISSUE TITLE
data-urlencode in request?

### ISSUE THREAD

**Issue by darksheik** [edgurgel/httpoison#109]
Hi!  More of a question than an issue.  Trying to build a simple request to send an SMS to Twilio.
Their docs say the cURL should look like this, and it works (secret info redacted):
```
curl -X POST 'https://api.twilio.com/2010-04-01/Accounts/<twilio_sid>/Messages.json' \
--data-urlencode 'To=<target_number>'  \
--data-urlencode 'From=+<my number>'  \
--data-urlencode 'Body=Test twilio post' \
-u <twilio_sid>:<twilio_auth>
```

I got the user authorization to work by eavesdropping on the headers and stealing the base64 encoded Authorization string, no problem.  But do you know how (if I can) I would add these --data-urlencode elements to my request?

What I have so far:
```
    response = HTTPoison.post!("https://api.twilio.com/2010-04-01/Accounts/<twilio_sid>/Messages.json",
      [],
      %{"Authorization": "Basic <b64 auth string>"}
          )
```

Thanks!

**Comment by darksheik** [comment]
Think I figured this out.

```
    response = HTTPoison.post!("https://api.twilio.com/2010-04-01/Accounts/AC9573ef9397dcfc6dec1371345f9d071e/Messages.json",
      'To=<target_number>&From=<my number>&Body=Test twilio post',
      %{"Authorization": "Basic QUM5NTczZWY5Mzk3ZGNmYzZkZWMxMzcxMzQ1ZjlkMDcxZTpmODY5ZDI2ZmZlNDZkYmFiMDI1N2QwOTliM2E4M2JiMA==",
        "Content-Type": "application/x-www-form-urlencoded"}
    )
```

Doesn't cover the URL-encoding portion (and there is probably a more elegant way to do this), but it does properly submit and I receive the SMS.

**Comment by darksheik** [comment]
Think I figured this out.  I'm building the URL-encoded body manually, but I can figure that out later.  It works:
```
response = HTTPoison.post!("https://api.twilio.com/2010-04-01/Accounts/<twilio_sid>/Messages.json",
      'To=<target_number>&From=<my number>&Body=Test twilio post',
      %{"Authorization": "Basic <b64 auth string>",
        "Content-Type": "application/x-www-form-urlencoded"}
    )
```

**Comment by edgurgel** [comment]
Hi @darksheik ! Can you try doing this:

https://github.com/edgurgel/httpoison/blob/master/test/httpoison_test.exs#L42-L46 

The body can be `{:form, [To: "target_number", From: "my number" ...]}`

**Comment by edgurgel** [comment]
I think you don't even need to pass the content-type header if you pass `:form` as body

**Comment by darksheik** [comment]
Hi @edgurgel - that totally works.  On both counts - body changed and didn't need to pass content-type.  Thank you!

**Comment by edgurgel** [comment]
Sweet!
