### ISSUE TITLE
Timeouts not working.

### ISSUE THREAD

**Issue by tslater** [edgurgel/httpoison#111]
I've tried all the timeouts I could find and my request is still timing out after only a few seconds. Am I missing something?

````
 response = HTTPoison.post("http://url.com/", Poison.encode!(params), [connect_timeout: 1000000, recv_timeout: 1000000, timeout: 1000000])
````
returns 
````
{:error, %HTTPoison.Error{id: nil, reason: :timeout}}
````

**Comment by edgurgel** [comment]
Yes you are missing the headers: http://hexdocs.pm/httpoison/HTTPoison.html#post/4

`post(url, body, headers \\ [], options \\ [])`

**Comment by tslater** [comment]
Oh shoots. Thanks!
