### ISSUE TITLE
Can't get headers in elixir 1.2

### ISSUE THREAD

**Issue by RobinClowers** [edgurgel/httpoison#113]
The access protocol now blows up if you try to give it a string:
```elixir
response.headers["Content-Encoding"]
```

Results in:
```
** (ArgumentError) the Access calls for keywords expect the key to be an atom, got: "Content-Encoding"
```

It looks like headers is a list of `{string, string}` tuples... Maybe it should be a map instead?

**Comment by edgurgel** [comment]
It has a good reason to not be a map (it was before): https://github.com/edgurgel/httpoison/pull/45

Sadly for now the only solution is to use [`List.keyfind/4`](http://elixir-lang.org/docs/v1.2/elixir/List.html#keyfind/4)

**Comment by edgurgel** [comment]
Or `:proplists.get_value/2`:

```
iex(1)> :proplists.get_value("content-type", [{"content-type", "application/json"}])
"application/json"
```

**Comment by RobinClowers** [comment]
Oh right, I guess that makes sense. Is it possible to write a custom access implementation? Or does the protocol prevent you from doing that?

**Comment by edgurgel** [comment]
It's not a protocol any more :( 

More info: https://github.com/elixir-lang/elixir/issues/4071

Apparently just lists with atom as keys (Keyword) are "meant" to be used with Access.

**Comment by edgurgel** [comment]
I will close the issue as this is something we can't change from where we stand.
