### ISSUE TITLE
Strange behavior with HTTPoison.post

### ISSUE THREAD

**Issue by sikanhe** [edgurgel/httpoison#116]
Hey so it seems like i am hitting some kind of bug with HTTPoison lib.
In all my other languages, i can successfully make the follow request to the url(should return 403)

https://EXERW3T3UB-dsn.algolia.net/1/indexes/*/queries

but with HTTPoison its returning 404

    %HTTPoison.Response{body: "{\"message\":\"Path not supported by Algolia REST API. Please have a       look at http://www.algolia.com/doc/rest_api for the list of valid commands\",\"status\":404}"

idk if something is different about how it encodes urls, it might have something to do with the * asterisk encoding

**Comment by edgurgel** [comment]
Thanks for opening the issue! It seems like a bug with the encoded URL. Can you share the exact hackney version you are using? It should be inside your `mix.lock` file

**Comment by sikanhe** [comment]
its {:hackney, "~> 1.4.4"}, but i think have tried to the latest hackney version(master branch) as well, also returns 404

**Comment by edgurgel** [comment]
I can't replicate your issue. I just used the same URL:

```
iex(1)> HTTPoison.get!("https://EXERW3T3UB-dsn.algolia.net/1/indexes/*/queries")
%HTTPoison.Response{body: "{\"message\":\"Invalid Application-ID or API key\",\"status\":403}",
 headers: [{"Server", "nginx"}, {"Date", "Fri, 22 Jan 2016 08:33:28 GMT"},
  {"Content-Type", "application/json; charset=UTF-8"}, {"Content-Length", "60"},
  {"Connection", "keep-alive"}, {"Access-Control-Allow-Origin", "*"},
  {"Cache-Control", "no-cache"}], status_code: 403}
```

HTTPoison 0.8.1 and Hackney 1.4.4

**Comment by sikanhe** [comment]
Sorry, i forgot to mention that it has to be a POST request

**Comment by edgurgel** [comment]
Oh ok! My bad!

**Comment by sikanhe** [comment]
I think this is now fixed in master https://github.com/benoitc/hackney/issues/272#issuecomment-174334135

**Comment by edgurgel** [comment]
Awesome!
