### ISSUE TITLE
Unable to catch hackney errors 

### ISSUE THREAD

**Issue by sikanhe** [edgurgel/httpoison#117]
I am trying to catch an argument error:

    try do     
         HTTPoison.get("")
    rescue
         _ -> "oops"      
    end

raises

** (exit) :badarg

same problem for :nil inputs

I think all this should be able to return {:error, reason} tuple for these scenarios using non-bang versions, so we never have to use try catch pattern as it is discouraged in elixir

**Comment by edgurgel** [comment]
Agreed! This is a bug :+1:
