### ISSUE TITLE
How to post json data to a url ?

### ISSUE THREAD

**Issue by ramstein74** [edgurgel/httpoison#118]
hello sorry its not an issue but a lack of info from the docs.

I want to post {"field1":"value1","field2":"value2"} to 
http://localhost:5984/mydb

i dont know how to do it with HTTPosion

i´m using this snippet but it does not work
![image](https://cloud.githubusercontent.com/assets/1210858/12550167/d8d8d268-c359-11e5-984b-52bb5ca57988.png)

**Comment by ramstein74** [comment]
I found the solution.thank you . Please delete this...

**Comment by edgurgel** [comment]
All good :+1:

**Comment by CJPoll** [comment]
@ramstein74 The solution would be nice to have posted here for future googlers like myself.
