### ISSUE TITLE
"unknown ca" error when posting 

### ISSUE THREAD

**Issue by brado** [edgurgel/httpoison#119]
I am getting the following error when I attempt  a post operation:
```
22:08:59.118 [error] SSL: :certify: ssl_handshake.erl:1490:Fatal error: unknown ca

** (FunctionClauseError) no function clause matching in Purest.MyAPI.handle_response/1
    (purest) lib/purest/my_api.ex:18: Purest.MyAPI.handle_response({:error, %HTTPoison.Error{id: nil, reason: {:tls_alert, 'unknown ca'}}})
```
I have no problems hitting this site within a browser or other HTTP client. I am using the following dependencies: 
- httpoison: 0.8.1
- hackney: 1.4.9

I am also using:
- Erlang/OTP 18
- Elixir 1.2

How can I fix this error? Thanks in advance.

**Comment by brado** [comment]
I have taken this further....and discovered that the problem is solved by specifying a cert file with a root CA as such: 
```
opts = [{:ssl_options, [{:cacertfile, "/Users/bohearne/Desktop/MyCertificates.pem"}]}]
HTTPoison.post(@body_login, @http_headers, hackney: opts)
```
That works. However, in my debugging of this problem, I've run into a brick wall on testing the above against hackney directly. I've tried testing the below in iex: 
```
opts = [{:ssl_options, [{:cacertfile, "/Users/bohearne/Desktop/MyCertificates.pem"}]}]
:hackney.get("https://<host>:<port>", opts)
```
This does not work, and gives the "unknown ca" error. I cannot find the error, and have reached out to other avenues for an answer, and others have said the same. So I'm happy to say that there isn't an issue in httpoison, so I'll close this issue. But given that the answer for how to address hackney with the options being sent to httpoison is somewhat wrapped up in whatever the httpoison layer does to alter those options and send them to hackney, I'd really appreciate it if someone in the know could set me straight on how to test hackney directly -- it will really help me in the future properly test httpoison issues, and properly isolate httpoison issues from hackney issues. Thanks!

**Comment by brado** [comment]
I am reopening this issue because I made the foolish assumption that options on GET operations were being handled similarly to options on POST operations. They are not, and there is a problem here. When using :dbg, looking at the output, when doing this: 
```
opts = [{:ssl_options, [{:cacertfile, "/Users/bohearne/Desktop/MyCertificates.pem"}]}]
HTTPoison.post(@body_login, @http_headers, hackney: opts)
```
this succeeds, because hackney passes the options properly to its underlying call to **hackney:maybe_proxy**. But if this same thing is attempted with a POST operation, as in: 
```
opts = [{:ssl_options, [{:cacertfile, "/Users/bohearne/Desktop/MyCertificates.pem"}]}]
HTTPoison.get(@url, hackney: opts)
```
this fails, same as the direct call to hackney, because hackney completely drops the options entirely to its underlying call to **hackney:maybe_proxy**. I do not know if this is ultimately a problem with hackney, or something httpoison is not sending in its call to hackney, so I'm reopening the issue.

**Comment by brado** [comment]
Odd....this is a parameter issue....but strange that it didn't manifest itself in a different manner. This was passed as a bad parameter all the way through httpoison and through hackney and even looking at debug output, it wasn't readily clear what the problem is. It would be great if either one of these libraries might have caught the problem at some point, but I'm glad that there isn't a bug.

**Comment by keyan** [comment]
@brado, I am seeing this issue right now. Could you elaborate on what your parameter issue was?

**Comment by edgurgel** [comment]
I would probably open an issue on hackney with your findings, @brado . I would consider this a bug :/
