### ISSUE TITLE
Nested post request params

### ISSUE THREAD

**Issue by holyxiaoxin** [edgurgel/httpoison#121]
I am trying to create a nested post request with the following as my params:

```
%{watchlist: %{chat_id: chat_id}}
```

So I tried: `HTTPoison.post(endpoint, {:form, [{:watchlists, Poison.encode!(%{chat_id: chat_id})}]})`
However, the value would be a json string on the endpoint.

I've also tried `HTTPoison.post(endpoint, Poison.encode!(%{watchlist: %{chat_id: chat_id}}), [{"Accept", "application/json"}])`

I can't get any params at the endpoint.

Are there any examples to do a post request with nested params?

**Comment by holyxiaoxin** [comment]
```
body = "watchlist[chat_id]=#{chat_id}"
HTTPoison.post(phoenix_endpoint('watchlists'), body, [{"Content-Type", "application/x-www-form-urlencoded"}])
```

The above works. But let me know that if there's a better solution to this (:

**Comment by holyxiaoxin** [comment]
Let me know if this needs a pr.

**Comment by edgurgel** [comment]
I'm not sure if "nested" form params are part of any RFC or if it's just a convention for some framework. If they are then we could send a PR to hackney.
