### ISSUE TITLE
Error: Ssl not started when using escript

### ISSUE THREAD

**Issue by Qqwy** [edgurgel/httpoison#127]
Following along the Programming Elixir book, I attempted to create the Github Issue formatter. It uses HTTPoison to grab a list of issues from the Github API.

I ran into #126 as well, and first applied the (at that time only) fix that adds an extra `config` option for hackney inside `onfig/config.exs`.

This worked fine, until I tried compiling the program using `mix exscript.build`. Building works, but attempting to run it afterwards gives the following stack trace:
~~~
** (FunctionClauseError) no function clause matching in Issues.GithubIssues.handle_response/1
    (issues) lib/issues/github_issues.ex:15: Issues.GithubIssues.handle_response({:error, %HTTPoison.Error{id: nil, reason: :ssl_not_started}})
    (issues) lib/issues/cli.ex:40: Issues.CLI.process/1
    (elixir) lib/kernel/cli.ex:76: anonymous fn/3 in Kernel.CLI.exec_fun/2
~~~

So, SSL is not started for some reason.

Going back to #126 and seeing the new mentioned fix of locking the Hackney version at `1.5.2` fixed this issue. So this does seem to be Hackney-related, although it was impossible to tell from the stack trace.

I am very confused as to why this behavior is different between when running it in `iex` and running it from the command line.

**Comment by edgurgel** [comment]
I think it was related to the way hackney was built with rebar3. Feel free to reopen if it's not working with the newest hackney.
