### ISSUE TITLE
Using HTTP Authentication easily?

### ISSUE THREAD

**Issue by seenickcode** [edgurgel/httpoison#128]
(Posting here because I'm not sure what Google Group/Forum to post to with this question)

I can't seem to find a way to easily include HTTP Authentication credentials when performing a request.  It seems the best way is to bake it into the base url like ``https://<username>:<pass>@<url>``.  

If I wrap httpoison though in a module, it seems like this is messy when overriding ``process_url/1``

Is there an ideal way to use HTTP Authentication with this library?  Thanks.

**Comment by teerawat1992** [comment]
@seenickcode I think you can use `[basic_auth: {"username", "pass"}]` as an option when make a request.

https://github.com/edgurgel/httpoison/blob/master/test/httpoison_test.exs#L75-L78

**Comment by edgurgel** [comment]
Hi @seenickcode, as @teerawat1992 said you can pass this option and if you want to override some common behaviour that is not addressed by `HTTPoison.Base` you can always override:

```def request(...) do
   options = [hackney: [basic_auth: {"username", "pass"}]]
   super(...., options)
```

This will always do the request with the options you wanted.

**Comment by seenickcode** [comment]
Great!  Thank you very much for the help guys!

**Comment by mariusbutuc** [comment]
As of [v0.11.1](https://github.com/edgurgel/httpoison/releases/tag/v0.11.1), have a look at `HTTPoison.Base.process_request_options/1` added in #208 instead.

**Comment by collegeimprovements** [comment]
Can this be done via `config.exs` ?

**Comment by willricketts** [comment]
@edgurgel This solved a similar problem I was having with including Twilio api credentials in requests using HTTPoison.

The specific bit you mentioned fixed my issue: `[hackney: [basic_auth: {"username", "pass"}]]`

What exactly is happening there? It fixed my issue, but I'd really like to know why.
