### ISSUE TITLE
Encoding problem in response's body

### ISSUE THREAD

**Issue by douglascamata** [edgurgel/httpoison#129]
Hello, I found an encoding problem while making a POST request. The server sends the string and says its encoding is `iso-8859-1`, but as soon as I inspect the body I can already see some utf-8 replacement characters. You can reproduce it using this code:

```elixir
wsdl_url = "https://apps.correios.com.br/SigepMasterJPA/AtendeClienteService/AtendeCliente"
xml = """
<?xml version="1.0" encoding="UTF-8"?>
    <soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:cli="http://cliente.bean.master.sigep.bsb.correios.com.br/">
      <soapenv:Header />
      <soapenv:Body>
        <cli:consultaCEP>
          <cep>01001000</cep>
        </cli:consultaCEP>
      </soapenv:Body>
    </soapenv:Envelope> 
"""
{:ok, %HTTPoison.Response{status_code: 200, body: body}} = HTTPoison.post(wsdl_url, xml)
IO.inspect body
```

Any ideas of how to fix this?

**Comment by edgurgel** [comment]
This should have nothing to do with `HTTPoison` but how Strings are handled by Elixir itself (which should be UTF-8). From my knowledge HTTPoison and hackney itself does not convert the body to any sort of encoding. 

I would ask around on Stackoverflow on how to deal with different char-sets. 

A quick google gave me this: https://www.reddit.com/r/elixir/comments/39azpw/character_encoding_conversion_in_elixir/

A reasonable web server would allow the client to select the char-set as part of the headers you send.

**Comment by douglascamata** [comment]
@edgurgel thanks. I'll close this as this isn't HTTPoison's fault.
