### ISSUE TITLE
Add process_request_options?

### ISSUE THREAD

**Issue by nicksanders** [edgurgel/httpoison#132]
Would you be interested in a pull request to add process_request_options so that default options can be set the same way as process_request_headers?

**Comment by edgurgel** [comment]
I would avoid adding another "callback" and suggest users to simply do this:

```elixir
defmodule MyClient do
  use HTTPoison.base

  def request(...) do
     options = [hackney: [basic_auth: {"username", "pass"}]]
     super(...., options)
  end
end
```

Similar issue: https://github.com/edgurgel/httpoison/issues/128#issuecomment-199019314

The reason would be that this is not really related to the HTTP request but a configuration of the HTTP client built on top of HTTPoison.

**Comment by nicksanders** [comment]
Like so?

````elixir
  def request(method, url, body \\ "", headers \\ [], options \\ []) do
     options = Keyword.merge([timeout: 2000, recv_timeout: 1000], options)
     super(method, url, body, headers, options)
  end
````

**Comment by edgurgel** [comment]
Yeah this should do the job! :ok_hand:
