### ISSUE TITLE
Ignoring cache

### ISSUE THREAD

**Issue by dtrce** [edgurgel/httpoison#137]
Is there a way to ignore caching even when the response of the http request is requesting to cache with header `Cache-Control` ?

**Comment by edgurgel** [comment]
Well the caching layer is always based on the headers that you send. AFAIK hackney, httpoison won't decide anything for you related to cached data. I'm not sure if I understood your question :/

**Comment by dtrce** [comment]
thanks. Using cache busting technique solves this problem.
