### ISSUE TITLE
SSL session being reused

### ISSUE THREAD

**Issue by filipecabaco** [edgurgel/httpoison#139]
Just wanted to report a weird behaviour while using HTTPoison.

It seems that sessions are being reused even when the ssl options flag `reuse_sessions: false` is set.

Thanks to this we are able to successfully make a HTTPS request with a invalid cert and key if previously a valid cert and key was used to make a request.

See https://github.com/filipecabaco/ssl_test to see a very small use case.

Am I missing something? Could this be a problem with Hackney? 

Thanks for the help.

**Comment by edgurgel** [comment]
That would be definitely an issue with Hackney. Do you mind opening the same issue there? 
Your use case will help a lot! 👍

**Comment by filipecabaco** [comment]
Ok will open and link this issue and example.

Thank you for checking it!
