### ISSUE TITLE
http2 support planned?

### ISSUE THREAD

**Issue by jschoch** [edgurgel/httpoison#140]
just wondering if you plan on supporting http2?

**Comment by edgurgel** [comment]
Not currently. I don't think HTTPoison has currently a reasonable interface for the amount of concurrency that http/2 needs. We would need to rethink the whole API.

**Comment by nathany** [comment]
I'm not sure what the API changes would be to use something like Chatterbox behind the scenes.

Of note, Go 1.6 added HTTP/2 client and server support without any API changes.
