### ISSUE TITLE
Weird responses when sending more than one request to a Cowboy server

### ISSUE THREAD

**Issue by dabaer** [edgurgel/httpoison#143]
I'm getting some unexpected results when firing HTTPoison request()'s within 1 second of each other. Every second request I am consistently seeing some sort of cached response, where it falls and hits one of my cases, but it doesn't ping the URL at all.

```
case HTTPoison.request(:post, url, file) do
    {:ok, %HTTPoison.Response{status_code: 200, body: []}} ->
        # Work
    {:ok, %HTTPoison.Response{status_code: 400, body: body}} ->
        # This clause gets hit the first time correctly based on the response from the endpoint, and it also hits it the second time, but without firing a request at the endpoint at all...
    _ ->
        # More work
end
```

Regards,
Dakota

P.S. I wait until the request is fully complete on both sides before hitting it again.

**Comment by dabaer** [comment]
Upon further inspection it's started falling through to the catch all clause.

```
{:ok,
 %HTTPoison.Response{body: "",
  headers: [{"connection", "close"}, {"server", "Cowboy"},
   {"date", "Fri, 10 Jun 2016 15:36:59 GMT"}, {"content-length", "0"}],
  status_code: 505}}
```

Phoenix fains no indication that a request reached it, so I guess Cowboy is intervening before it reached phoenix, but i'm not sure why.

**Comment by alakra** [comment]
bump

**Comment by edgurgel** [comment]
I would double check if your cowboy code is not mixing "req" records. https://github.com/ninenines/cowboy/issues/768

This may occur if you mix `conn` structs on Phoenix as well.

**Comment by edgurgel** [comment]
Just to exclude httpoison from this equation, set up an http server (using python, ruby, whatever) and send requests. You should get 505s.

**Comment by samrispaud** [comment]
[this solved things for me](http://stackoverflow.com/questions/12559575/typhoeus-does-not-close-https-connections) and again cowboy doesn't like re-used requests and typheous does this by default. hope this helps someone in the future
