### ISSUE TITLE
Timeouts when making POST requests

### ISSUE THREAD

**Issue by allyraza** [edgurgel/httpoison#153]
I am working on this paypal client using httpoison to make request all my post requests timeout initially I thought it was the manager genserver I had implemented after some head bashing I figured it out its httpoison

**Comment by clekstro** [comment]
Is it possible you're running into one of the [default timeouts](https://github.com/edgurgel/httpoison/blob/3139a0e12f8e3acb0d841b62a48f372b06f4700b/lib/httpoison/base.ex#L128-L129) (5s)?

**Comment by allyraza** [comment]
I increased that to like 15s tested it  before I reported it

**Comment by allyraza** [comment]
now hackney would not compile 

```
** (Mix) Could not compile dependency :hackney, "/Users/al-razi/.mix/rebar3 bare compile --paths "/Users/al-razi/work/merchant/_build/dev/lib/*/ebin"" command failed. You can recompile this dependency with "mix deps.compile hackney", update it with "mix deps.update hackney" or clean it with "mix deps.clean hackney"
```

**Comment by jc00ke** [comment]
I'm seeing this with `PUT` requests. I've bumped the timeout to 20s but it still times out after ~7s.

I've never had a `GET` time out, and I have't personally seen any `POST` timeouts either.

**Comment by jc00ke** [comment]
I set `recv_timeout: 10_000` and now the response is completing.

In my case the transaction on their end was being committed, so when I would issue a `GET` I would see the update, but the `PUT` itself was always timing out. It's probably got something to do with the way their API is returning the response.
