### ISSUE TITLE
feature request: process_response

### ISSUE THREAD

**Issue by nathany** [edgurgel/httpoison#157]
What do you think of having a `process_*` delegate for wrapping with `HTTPoison.Base` that can access both the body and the status code?

Currently I'm calling this function by hand after the request (and therefore after the other callbacks such as `process_response_body`).

```elixir
# Process OK response (performed manually, not a Poison callback)
def process_response({:ok, resp}) do
  case resp.status_code do
  200 -> {:ok, resp.body}
  _ -> Error.new(resp)
  end
end

def process_response({:error, error}) do
  {:error, error}
end
```

**Comment by edgurgel** [comment]
I would argue pretty much the same I did here: https://github.com/edgurgel/httpoison/issues/132

**Comment by nathany** [comment]
Thanks. I didn't know about `super`.
