### ISSUE TITLE
SSL Handshake failure

### ISSUE THREAD

**Issue by Frogglet** [edgurgel/httpoison#160]
Any reason why httpoison/hackney wouldn't be able to complete the handshake with the server at https://rev-int.api.us.fleetmatics.com? When I try to connect I get `{:error, %HTTPoison.Error{id: nil, reason: :closed}}` with no other info. I've run the server through the ssl labs test and it passes all handshake tests. Also, I can connect to it via node and curl just fine. 

I'm not a networking guy, but in wireshark, it appears that right after hackney sends a ClientHello packet, the server responds with a packet that specifies a connection reset, and thats the last thing sent by either party.

**Comment by Frogglet** [comment]
Closed this issue as it is not specific to hackney or httpoisons - appears to be an erlang issue.

**Comment by sunboshan** [comment]
@Frogglet have you resolve this issue yet? I have the exact same problem when accessing https://play.google.com. 

```
iex> HTTPoison.get("https://play.google.com")
{:error, %HTTPoison.Error{id: nil, reason: :closed}}
```

Why it's an Erlang issue?

**Comment by edgurgel** [comment]
Can you guys share the Erlang and Elixir version so we can track if this an SSL issue (that is causing the connection to close?)

**Comment by sunboshan** [comment]
```
Erlang/OTP 19 [erts-8.0.2] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]

Interactive Elixir (1.3.2) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> HTTPoison.get("https://www.youtube.com")
{:error, %HTTPoison.Error{id: nil, reason: :closed}}
```

Quick fix in #130

**Comment by nurey** [comment]
Erlang/OTP 19 [erts-8.0.2] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

IEx 1.3.2

**Comment by danturn** [comment]
same issue here:

Erlang/OTP 19 [erts-8.0.5] [source] [64-bit] [smp:4:4] [async-threads:10] [kernel-poll:false]

Interactive Elixir (1.3.3) - press Ctrl+C to exit (type h() ENTER for help)

**Comment by suddenrushofsushi** [comment]
Same issue here (httpoison 0.10.0):

Erlang/OTP 19 [erts-8.2] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false]
Interactive Elixir (1.4.2) - press Ctrl+C to exit (type h() ENTER for help)

Of interest, the [bug](https://bugs.erlang.org/browse/ERL-192) listed in the documentation was marked as `Resolved/Not a Bug` Aug 30, 2016; I don't think you should note using the TLS 1.2 option as a workaround until it's "fixed".

I have no problem implementing the workaround, but this looks like something that should be investigated further in HTTPoison or perhaps Hackney as the erl bug listed is defunct.
