### ISSUE TITLE
Cookie for POST requests

### ISSUE THREAD

**Issue by jfpalngipang** [edgurgel/httpoison#162]
How do I append the cookie on my post requests? An error about badarg is always showing after several attempts.

**Comment by katgironpe** [comment]
@jfpalngipang through metaprogramming. Use `defp process_request_headers(headers)`. Ideally should not be using HTTPoison as is. We normally create a wrapper. The example is on the README file.

**Comment by edgurgel** [comment]
@jfpalngipang, can you show us some code so we can help/guide you? As @katgironpe said you can customise the way that HTTPoison will deal with your requests.
