### ISSUE TITLE
socks5 proxy options not working

### ISSUE THREAD

**Issue by anhhh11** [edgurgel/httpoison#167]
I see that normal request or through http proxy work well but socks5 option not recognized
:hackney.request(:get,"https://www.whatismyip.com",[],"",[{:proxy,{:socks5,'27.105.50.243',8080}}])
-> working

HTTPoison.get! "https://www.whatismyip.com", %{}, [proxy: {:socks5,"189.51.104.231",43803}]
** (HTTPoison.Error) :badarg
(httpoison) lib/httpoison.ex:66: HTTPoison.request!/5

**Comment by edgurgel** [comment]
@anhhh11, the difference here is that the `ip` is an Erlang string for the hackney example but a binary for HTTPoison. Could you try with `'189.51.104.231'` instead of `"189.51.104.231"`

Feel free to reopen if this is not the case!
