### ISSUE TITLE
Errors inside process_response_* callbacks are swallowed.

### ISSUE THREAD

**Issue by mootpointer** [edgurgel/httpoison#168]
In `HTTPoison.Base.request`, the error handling around Hackney is useful for catching any errors inside the request/response cycle. However, this error handling also means that any errors which occur inside the `process_response_* callbacks get swallowed. That can make it hard to debug anything happening inside that method.

Because it's a private method, it can be hard to test in isolation.

What do you think about doing something to improved the bubbling of errors up from here?

(The offending catch is here: https://github.com/edgurgel/httpoison/blob/master/lib/httpoison/base.ex#L414)

**Comment by mootpointer** [comment]
Looking deeper, I found #141, it looks like the intention was to catch any Hackney errors. This is a laudable aim, but the current solution catches much more than just the Hackney errors.

I'll work on a patch which still catches the hackney errors but also bubbles up any processing exceptions.

**Comment by mootpointer** [comment]
25 minutes later, #169 appeared.

**Comment by edgurgel** [comment]
As soon as I release a new version we can close this issue? 👍 (Hopefully today)

**Comment by mootpointer** [comment]
Brilliant.

Thanks!

On Mon, 29 Aug 2016 at 8:32 AM Eduardo Gurgel

<
mailto:Eduardo Gurgel <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

As soon as I release a new version we can close this issue?

👍

(Hopefully today)

—

You are receiving this because you authored the thread.

Reply to this email directly,
https://github.com/edgurgel/httpoison/issues/168#issuecomment-243003688
, or

**Comment by edgurgel** [comment]
🎉 https://github.com/edgurgel/httpoison/releases/tag/v0.9.1
