### ISSUE TITLE
HTTPoison.request! produces cover compilation error in using modules on OTP 19

### ISSUE THREAD

**Issue by seancribbs** [edgurgel/httpoison#177]
Using `Kernel.raise/1` in `HTTPoison.Base.request!` forces creation of a case clause that uses the `location: -1` annotation. This version of line tracking is not supported or broken on OTP 19. 

To avoid problems in OTP 19, one should make the following change:

```diff
  def request!(method, url, body \\ "", headers \\ [], options \\ []) do
    case request(method, url, body, headers, options) do
      {:ok, response} -> response
-     {:error, error} -> raise error
+     {:error, %Error{reason: reason}} -> raise Error, reason: reason
    end
  end
```

Related Elixir issue: elixir-lang/elixir#5257
Related coveralls issue: parroty/excoveralls#60

**Comment by seancribbs** [comment]
Note this error is resolved on the 1.3 and master branch of Elixir, but the above diff would resolve the issue for HTTPoison until that is released (and on older versions of Elixir).

**Comment by edgurgel** [comment]
@seancribbs, thanks! I will release a new version soon with the proposed patch.

Thanks for the bug report and also for `neotoma` (I've been playing with it for a couple of weeks)

**Comment by seancribbs** [comment]
You're welcome! (lol `neotoma`, my albatross)

**Comment by edgurgel** [comment]
https://github.com/edgurgel/httpoison/releases/tag/v0.9.2 is out! 🎉

**Comment by seancribbs** [comment]
Thanks so much! I've upgraded and it works as advertised. 😄
