### ISSUE TITLE
Support of arrays as query parameters

### ISSUE THREAD

**Issue by imetallica** [edgurgel/httpoison#181]
Hi, I'm on a situation that I need to send an array as a parameter in the url. Is there a way to do it?

**Comment by edgurgel** [comment]
I don't think we implement any array support for query string params. I'm not even sure if there's a real standard (RFC etc) that defines this...

**Comment by shhavel** [comment]
@edgurgel 
I think it may be fixed in elixir - https://github.com/elixir-lang/elixir/pull/5282
But not sure if they will approve this pull request.

@imetallica 
As a temporary fix you can use patched version of **httpoison**.
If so, add this into your `mix.exs` dependencies:

```elixir
def deps do
  [{:httpoison, github: "shhavel/httpoison", branch: "feature/array_query_param", override: true}]
end
```

**Comment by imetallica** [comment]
Great, I'll give a shot at it @shhavel. Thanks! 👍

**Comment by shhavel** [comment]
@imetallica 
Actually there is no clear standard how to pass array value in GET parameters.
E.g. an array `a = [1, 2, 3]` can be encoded differently in URL: `a[]=1&a[]=2&a[]=3`  (with encoded square brackets) or just `a=1&a=2&a=3`.
You can control this and provide any version without a patch, with keyword lists:

```elixir
HTTPoison.get("localhost:8080/get", [], params: [{:a, 1}, {:a, 2}, {:a, 3}])

HTTPoison.get("localhost:8080/get", [], params: [{"a[]", 1}, {"a[]", 2}, {"a[]", 3}])
```

I see 2 possibles solutions for this issue:
1. Leave it as it is and maybe update the docs for  `HTTPoison.get/3`
2. Support arrays as query parameters with configuration option how it's key should be encoded (with or without square brackets).  
@edgurgel How do think?

**Comment by imetallica** [comment]
@shhavel the problem is that I have an array of objects, like:
```
foo: [ {bar: 1}, {baz: 2} ]
```

And these deep objects can have arrays inside them as well. Well, I'll try your repo and see how it goes, until Elixir solves the `URI` issue you pointed out.

**Comment by imetallica** [comment]
Just a side-note, `Plug` supports this: https://hexdocs.pm/plug/1.2.2/Plug.Conn.Query.html

So, it's just a matter of adding that to the URL before sending.

**Comment by shhavel** [comment]
@imetallica 
I've created micro package - https://github.com/shhavel/uri_query
for preparing parameters before being URI encoded, e.g.:

```elixir
iex> params = %{user: %{name: "Dougal McGuire", email: "test@example.com"}} |> UriQuery.params
[{"user[email]", "test@example.com"}, {"user[name]", "Dougal McGuire"}]
iex> HTTPoison.get("http://example.com", [], params: params)
```

or with list value

```elixir
iex> UriQuery.params(foo: ["bar", "quux"]) |> URI.encode_query
[{"foo[]", "bar"}, {"foo[]", "quux"}]
```

So [httpoison](https://github.com/edgurgel/httpoison/) may be used without a patch.

**Comment by edgurgel** [comment]
I'm closing this issue as there is no standard out there. Thanks everyone

**Comment by yanshiyason** [comment]
Is it possible to append to the url an arbitrary string?
