### ISSUE TITLE
Instrumentation

### ISSUE THREAD

**Issue by jclem** [edgurgel/httpoison#183]
Is there an established way to instrument HTTPoison? At the least, I'd like to reliably measure all outgoing request times.

**Comment by edgurgel** [comment]
Yes we have some kind of instrumentation! Hackney supports a bunch of metrics:

https://github.com/benoitc/hackney#metrics

Would this be enough for your use case?

**Comment by jclem** [comment]
Ah, didn't think of looking at hackney. It might—my goal is to actually send events to [AppSignal](https://appsignal.com) as part of request transactions.

**Comment by edgurgel** [comment]
Another way to get this is to override `request/5` and do something around it:

```
defmodule MyClient do
  use HTTPoison.base

  def request(...) do
     options = [hackney: [basic_auth: {"username", "pass"}]]
     started_at = Time.now 
     result = super(...., options)
     finished_at = Time.now
     AppSignal.send(....)
     result
  end
end
```
