### ISSUE TITLE
Support unix sockets (hackney 1.6.2)

### ISSUE THREAD

**Issue by rhruiz** [edgurgel/httpoison#185]
Hello,

hackney recently introduced support for making requests on unix sockets using the scheme `http+unix://`. The following code on `base.ex` prepends an extra `http://` on the url breaking the request:

```
@doc false
def default_process_url(url) do
  case url |> String.slice(0, 8) |> String.downcase do
    "http://" <> _ -> url
    "https://" <> _ -> url
    _ -> "http://" <> url
  end
end
```

As a workaround, I can implement my own module with the HTTPoison.Base macro and override `process_url`.

Can we get that allowed on the default_process_url as well?

Thanks!

**Comment by edgurgel** [comment]
Definitely! Do you mind sending a PR for this change?

**Comment by rhruiz** [comment]
Sure thing, just had to add unix sockets to httparrot to write the tests: https://github.com/edgurgel/httparrot/pull/23

I will send the PR next
