### ISSUE TITLE
Hook to process the whole request/response instead of each part separately 

### ISSUE THREAD

**Issue by loicvigneron** [edgurgel/httpoison#193]
I would be cool to have some hook that allow to process the whole request or response instead of status code, body and headers separately.

For example, when I want to define a domain specific HTTP client, I need check if the _status_ code is not >= 400 and if it's the case, raise an error with the content of the _body_. At this time, it's only possible to check the body or the status code separately and so difficult to achieve this behaviour.
The idea is to have a new `process_response` hook that gets the whole response:
  
```
defp process_response(response) do
    case response do
      %HTTPoison.Response{status_code: 200, body: body} ->
        %{response | body: Poison.decode!(body)}
      %HTTPoison.Response{status_code: status_code, body: body} when status_code >= 400 ->
        attributes = Poison.decode!(body)
        raise MyDomain.CustomError, message: attributes["error"]["message"]
      _ ->
    end
  end
```

There is the quick test I made in [my fork](https://github.com/loicvigneron/httpoison/commit/7054d5560e0e69a0d183ee0fd928d97d5e531ece). If you are okay with the idea, I can make something a bit better and tested :)

**Comment by edgurgel** [comment]
I would probably advocate for this solution: https://github.com/edgurgel/httpoison/issues/132#issuecomment-214554957

**Comment by loicvigneron** [comment]
And that would be perfect :) 👍
