### ISSUE TITLE
Generate header based on URL?

### ISSUE THREAD

**Issue by naps62** [edgurgel/httpoison#206]
I'm building an API client using the `HTTPoison.base` module.

The api I'm connecting to requires a rather complex authorization header, which is a function of several values, one of which is the full request URL.

As an example, I want to do:

```
MyClient.get "/some-endpoint"
```

And the authorization header will have to take into account the full URL, `https://domain/some-endpoint`

`process_request_headers` only gives me the `header` argument, so the only way I was able to do this so far was by overriding `def request(method, url, body, headers, options)` only to change the part where headers are generated

Is there a better way here?

**Comment by edgurgel** [comment]
That's the approach I would take to accomplish what you need. The `process_` callbacks are simple functions to modify the components of the HTTP request. If you need something more complex overriding the `request` method is the way to go. 👍

**Comment by naps62** [comment]
Ok, I got no problem with that. Just wanted to see if I was missing something :)
