### ISSUE TITLE
Using `HTTPoison.Base` results in compiler warnings in 1.4

### ISSUE THREAD

**Issue by sotojuan** [edgurgel/httpoison#207]
Essentially, the warnings are like this one:

`making private functions (process_request_headers/1 in this case) overridable is deprecated`

From Slack:

> Probably due to https://github.com/edgurgel/httpoison/blob/master/lib/httpoison/base.ex#L349
> should probably be `Module.definitions_in __MODULE__, :def`

**Comment by aquarhead** [comment]
Fixed by https://github.com/edgurgel/httpoison/pull/201 ?

**Comment by sotojuan** [comment]
Will have to try from master, thanks.

**Comment by sotojuan** [comment]
Yup, works on master. Thanks. @edgurgel can we have a release?

**Comment by edgurgel** [comment]
0.11.0 is out! Hopefully we can get 1.0 out soon after this release! Thanks!

https://github.com/edgurgel/httpoison/releases/tag/v0.11.0
