### ISSUE TITLE
Timeout option seems to be ignored.

### ISSUE THREAD

**Issue by ospaarmann** [edgurgel/httpoison#211]
When calling an API endpoint that returns a larger JSON blob (1.4 MB) like so:

`HTTPoison.get(url, [], [timeout: 50_000])`

I always receive a 

`{:error, %HTTPoison.Error{id: nil, reason: :timeout}}`

error. The timeout option seems to be ignored since this happens long before the timeout that I defined. Calling the same endpoint with the same timeout value from the same machine with HTTPotion works.

I'm using `{:httpoison, "~> 0.9.2"}` on elixir 1.3.

Any ideas what could cause this?

**Comment by edgurgel** [comment]
Oh Hey! I would check if the `recv_timeout` is the one that is timing out. From the docs:

```
Options:

:timeout - timeout to establish a connection, in milliseconds. Default is 8000
:recv_timeout - timeout used when receiving a connection. Default is 5000
```

Could you try increasing both?

I'm pretty sure hackney considers them both "timeout" errors but it doesn't specify why it timed out. It can be confusing :/

**Comment by ospaarmann** [comment]
That solved the issue for me. Thank you for the feedback.

`HTTPoison.get(url, [], [timeout: 50_000, recv_timeout: 50_000])`
