### ISSUE TITLE
warning: making private functions overridable is deprecated

### ISSUE THREAD

**Issue by austinsmorris** [edgurgel/httpoison#212]
At the end of the `__using__` macro in `HTTPoison.Base` is the line:

    defoverridable Module.definitions_in(__MODULE__)

This makes all functions defined in the module overridable including private functions.  This behavior is deprecated in elixir 1.4 and now throws a warning at compile time.  

Only public functions can be overridable they and must be listed explicitly when using `defoverridable`.

**Comment by edgurgel** [comment]
Which version of HTTPoison did you use? The latest one should fix this issue!

**Comment by edgurgel** [comment]
More about the latest release here: https://github.com/edgurgel/httpoison/releases/tag/v0.11.0

**Comment by austinsmorris** [comment]
You're right, sorry.  Thanks!
