### ISSUE TITLE
NXDomain when using params

### ISSUE THREAD

**Issue by JeremyBellows** [edgurgel/httpoison#214]
Hello

I have the following code block
```
url = localhost
params = [{"param1", "value"}, {"param2", "value"}, {"param3", "value"}]
response = HTTPoison.get(url, [], params: params)
```

The error `nxdomain` is returned. The localhost server is up and accessible via browser. When I use a known public domain like "www.google.com" the error is still returned. When the params are removed from the function call, the request is successful.

**Comment by JeremyBellows** [comment]
I figured it out.

The domain needs to have a `/` on it for proper execution.

**Comment by Gyllsdorff** [comment]
I just ran into this, if it is the expected behaviour it should be documented somewhere.

**Comment by leogottardi** [comment]
Thanks for your solution, solved my problem. Who would have thought that the lack of "/" would cause that.
