### ISSUE TITLE
Follow Post Redirect on Any Status

### ISSUE THREAD

**Issue by liveresume** [edgurgel/httpoison#216]
I am trying to POST to an endpoint that always redirects and sets status_code=302.

```elixir
{:ok, response} = HTTPoison.post(url, body, headers, follow_redirect: true, max_redirect: 20 )
```
I [read](https://github.com/benoitc/hackney/blob/master/README.md#automatically-follow-a-redirection) that only 303 returned on a POST will follow redirects.  So I believe that is why it's not working.

How can I make it ignore the status code and follow the redirect?

**Comment by edgurgel** [comment]
Sorry for the delay but hackney supports an option `force_redirect`: https://github.com/benoitc/hackney/blob/6046b342accf6c8f394c87b08ebe92c748c1f4df/src/hackney.erl#L117
