### ISSUE TITLE
Avoiding escaping url

### ISSUE THREAD

**Issue by kostonstyle** [edgurgel/httpoison#218]
Hi all

Is there a way to avoid URL escaping.
For example, I have following URL

> http://localhost:3000/LoginInfoSet(Username='BMA')

and it will escaped to

> /LoginInfoSet%28Username=%27BMA%27%29

How can I avoid that? The problem is ().

I tried with C# httpclient and I've got the expected result. I think () does not get escaped. 

Thanks

**Comment by edgurgel** [comment]
🤔 ... The encoding of URLs is completely done hackney side so I would check how hackney encode the URL

**Comment by kostonstyle** [comment]
Thanks so much.

**Comment by amarsahinovic** [comment]
In case it helps somebody, I had the same issue and I used the undocumented :hackney option to make it work, here is an example:
~~~
hn_options = [{:path_encode_fun, fn (path) -> path end}]
options = Keyword.merge(options, [{:hackney, hn_options}])
~~~

I got the idea from this issue: https://github.com/benoitc/hackney/issues/314
