### ISSUE TITLE
1.0 Release soon?

### ISSUE THREAD

**Issue by drapergeek** [edgurgel/httpoison#225]
First of all, thank you for httpoison! This is a great library that I've enjoyed using in a lot of different ways!

Would it be possible to release a 1.0 soon?

Right now, a lot of members in the community are running into conflicts when trying to upgrade apps because so many other libraries depend on httpoison. In my current project, I have 3 different libraries which are all requesting a different version of httposion. In an ideal world, I would request that those libraries loosen their version constraint but if you're following semver, it's unreliable to believe that pre-1.0 the interface will stay the same.

Thanks again!

**Comment by edgurgel** [comment]
Yes I'm keen to sit down and release a stable 1.0.0 version. I think it should happen sooner than later. Thanks for starting this conversation.

**Comment by sashaafm** [comment]
Any news on this? It's been almost a year :)

**Comment by edgurgel** [comment]
I think it's time to simple upgrade our current version to 1.0.0 🤔

**Comment by edgurgel** [comment]
Done! 🎉
