### ISSUE TITLE
Issue with hackney 1.6.6

### ISSUE THREAD

**Issue by raymondboswel** [edgurgel/httpoison#226]
I noticed that my external calls on our development server started failing. After some head scratching and posting to requestb.in I noticed that the content-type header is duplicated as follows:

Content-Type: application/json, application/json

When I updated my local hackney to 1.6.6 I found the same behaviour. I'm not sure if this is a bug with HTTPoison or hackney, so posting here first. 

My project uses Elixir 1.4.2 and HTTPoison 0.9.2.

**Comment by nlap** [comment]
Looks like a fix is coming at benoitc/hackney#388

To get up an running in the meantime I set `{:hackney, "1.6.5", override: true}`

**Comment by xinz** [comment]
@nlap, thanks for your rollback suggestion before fix in the hackney 1.6.6

**Comment by raymondboswel** [comment]
That's what I also ended up doing. Thanks!

**Comment by Moxide** [comment]
Whoah, this one made me sweat a lot !!! A project suddenly stopped sending mail through Bamboo, had to debug it down to hackney...
Thanks @nlap !

**Comment by xinz** [comment]
This issue has been fixed by hackney https://github.com/benoitc/hackney/issues/388 , please upgrade to hackney 1.7.0 to verify your case.

**Comment by xinz** [comment]
Before the PR https://github.com/edgurgel/httpoison/pull/228 is accepted, we can manually upgrade with the hackney fixing in the mix project`mix.exs` as:

```Elixir
 {:hackney, "~> 1.7.0", override: true},
```

**Comment by edgurgel** [comment]
https://github.com/edgurgel/httpoison/releases/tag/v0.11.1 0.11.1 has this fix! Thanks!
