### ISSUE TITLE
value of content-type request is duplicated 

### ISSUE THREAD

**Issue by zentechnamhoang** [edgurgel/httpoison#227]
I request with method POST to a server by: 

`HTTPoison.post("http://localhost:3000/api/post", "{\"amount\":\"15.47\",\"currency\":\"cad\",\"customer_id\":\"ab972af151718211b35ea820b4811586\",\"customer_id_app\":\"cus_ACX2qzxvsDI2vhasd\",\"order_id\":\"ordere80e299bcc82570051d3f130c0e42f10\",\"request_id\":\"1\",\"ticket_id\":\"1B21969F-D91A-4142-A4D5-3B3787EF132D\",\"token\":\"d69270f442009422ef8e34173e531464\",\"type\":\"dinein\"}", [{"Content-type", "application/json"}])`

     Then, I receive `conn` from this POST on server port 3000 such as:

`%Plug.Conn{adapter: {Plug.Adapters.Cowboy.Conn, :...}, assigns: %{},
 before_send: [#Function<4.40807080/1 in Phoenix.Controller.fetch_flash/2>,
  #Function<0.46198565/1 in Plug.Session.before_send/2>,
  #Function<1.3471277/1 in Plug.Logger.call/2>,
  #Function<0.88006395/1 in Phoenix.LiveReloader.before_send_inject_reloader/2>],
 body_params: %{}, cookies: %{}, halted: false, host: "localhost",
 method: "POST", owner: #PID<0.392.0>, params: %{},
 path_info: ["webhook", "charge"], path_params: %{},
 peer: {{127, 0, 0, 1}, 49484}, port: 3000,
 private: %{PaymentGateway.Router => {[], %{}},
   :phoenix_action => :receive_info_charge,
   :phoenix_controller => PaymentGateway.Webhook.WebhookController,
   :phoenix_endpoint => PaymentGateway.Endpoint, :phoenix_flash => %{},
   :phoenix_format => "json",
   :phoenix_layout => {PaymentGateway.LayoutView, :app},
   :phoenix_pipelines => [:webhook],
   :phoenix_route => #Function<2.57028329/1 in PaymentGateway.Router.match_route/4>,
   :phoenix_router => PaymentGateway.Router,
   :phoenix_view => PaymentGateway.Webhook.WebhookView, :plug_session => %{},
   :plug_session_fetch => :done}, query_params: %{}, query_string: "",
 remote_ip: {127, 0, 0, 1}, req_cookies: %{},
 req_headers: [{"content-type", "application/json, application/json"},
  {"user-agent", "hackney/1.6.6"}, {"host", "localhost:3000"},
  {"content-length", "304"}], request_path: "/webhook//charge", resp_body: nil,
 resp_cookies: %{},
 resp_headers: [{"cache-control", "max-age=0, private, must-revalidate"},
  {"x-request-id", "72om3afqhhmf2crppei3o7k3hd8b5kvn"}], scheme: :http,
 script_name: [],
 secret_key_base: "OKceueH/NwrbdA0C5FF86hPW+WMMAsonul0lkZ0dsBTZmnE9acPSgiYjuik6Qcw0",
 state: :unset, status: nil}`

`{"content-type", "application/json, application/json"}` value of content-type is duplicated

     My deps: 

    `[{:phoenix, ">= 1.2.0"},
     {:phoenix_ecto, "~> 3.0.0"},
     {:postgrex, ">= 0.11.2"},
     {:phoenix_html, "~> 2.9.3"},
     {:phoenix_live_reload, "~> 1.0.8"},
     {:cowboy, ">= 1.1.2"},
     {:jazz, "~> 0.2.1"},
     {:httpoison, "~> 0.11.0"},
     {:poison, "~> 2.2.0"},
     {:hackney, "~> 1.6"},
     {:uuid, "~> 1.1.6"},
     {:exjsx, "~> 4.0.0"}]`

**Comment by dimun** [comment]
@zentechnamhoang how did you resolve this issue? I am in the same situation, thanks

**Comment by edgurgel** [comment]
@dimun, what's the hackney version you are using?

**Comment by dimun** [comment]
@edgurgel, I have updated my httpoison version, to 0.11.1 and everything is working well, thanks
