### ISSUE TITLE
Duplicated Headers sent with POST

### ISSUE THREAD

**Issue by jakehasler** [edgurgel/httpoison#234]
Referencing [this issue](https://github.com/benoitc/hackney/issues/388), when sending a POST request from a client that extended HTTPoison.Base, the content-type header was getting duplicated to: `"Content-Type": "application/json, application/json"` which was causing it to fail.

Suggested Change: Update hackney in the httpoison deps to `1.7.1`.

Thanks!

**Comment by edgurgel** [comment]
Cool let's update the dependency!

**Comment by zac156** [comment]
Had this issue too. Update worked. Thanks
