### ISSUE TITLE
Update docs with Hackney SSL options

### ISSUE THREAD

**Issue by rohannair** [edgurgel/httpoison#242]
There's a lack of official documentation around this feature: Related to https://github.com/edgurgel/httpoison/pull/77

Took me quite a while to figure out how to use SSL with httpoison. Might be good to add :)

**Comment by edgurgel** [comment]
Oh yeah definitely! 👍

**Comment by nashby** [comment]
Documentation was added here https://github.com/edgurgel/httpoison/pull/252 @edgurgel you can close it :)
