### ISSUE TITLE
Broke my Erlang installation using Readme instructions

### ISSUE THREAD

**Issue by denispeplin** [edgurgel/httpoison#245]
https://github.com/edgurgel/httpoison#if-youre-on-ubuntu

`apt-get install erlang-dev` installed package for Erlang 18.3, but I had 19.3 installed. After installation I've got a problem like this: https://github.com/phoenixframework/phoenix/issues/1720

Healed by `sudo apt-get autoremove erlang-dev`, which also removed Erlang, and re-installing Erlang.

**Comment by edgurgel** [comment]
Thanks for the report. Feel free to send a PR!

**Comment by denispeplin** [comment]
My PR will be to remove this thing about `apt-get install erlang-dev` and whole `Ubuntu` section with it, because it doesn't contain anything else.

But I don't know what it for, maybe it is useful in some setups. I have Erlang installed from this site: https://www.erlang-solutions.com/resources/download.html and `HTTPoison` works fine without `erlang-dev`.

**Comment by edgurgel** [comment]
Yeah I tend to agree that this is not useful anymore

**Comment by edgurgel** [comment]
I will remove the section
