### ISSUE TITLE
How does the proxy option work?

### ISSUE THREAD

**Issue by mvalitov** [edgurgel/httpoison#248]
I tried to make a request through a proxy in many ways:
```
  def ping(%{url: url, proxy: proxy}) do
    options = [proxy: proxy]
    case HTTPoison.request(:get, url, "", [], options) do
      {:ok, response} ->
        %HTTPoison.Response{body: body, headers: list, status_code: integer} = response
        body
      {:error, reason} ->
        reason
    end
  end
```

`ping(%{url: "https://api.ipify.org", proxy: 'http://127.0.0.1:8118'})`
```
  00:19:08.675 [error] SSL: :hello: ssl_alert.erl:88:Fatal error: internal error
  %HTTPoison.Error{id: nil, reason: {:tls_alert, 'internal error'}}
```

`ping(%{url: "https://api.ipify.org", proxy: {:http, '127.0.0.1', 8118}})`
`"188.162.198.156" - This is my ip without a proxy`

```
curl 'https://api.ipify.org' --proxy "http://127.0.0.1:8118"
195.228.45.176
```

In what form do I need to pass options to use a proxy?

**Comment by mvalitov** [comment]
As I see from the documentation, the syntax is
`ping(%{url: 'https://api.ipify.org', proxy: 'http://127.0.0.1:8118'})`
Just can not fix the error
```
13:46:09.153 [error] SSL: :hello: ssl_alert.erl:88:Fatal error: internal error
%HTTPoison.Error{id: nil, reason: {:tls_alert, 'internal error'}}
```
The `options = [proxy: proxy, ssl: [{:verify, :verify_none}]]` option does not help

**Comment by mvalitov** [comment]
The reason was in the service itself

**Comment by mukulpanchal** [comment]
@mvalitov - Did it work for you? I am coming across similar issue.


as per the doc I have tried:
{proxy: {PROXY_HOST:PROXY_PORT}}
{proxy: {PROXY_HOST, PROXY_PORT}}

Neither of them seem to work

**Comment by mvalitov** [comment]
@mukulpanchal, for me it worked 
`[proxy: {:socks5, String.to_charlist(uri.host), uri.port}]`
