### ISSUE TITLE
how to fully override user-agent?

### ISSUE THREAD

**Issue by dweinstein** [edgurgel/httpoison#249]
there's a fussy server that won't respond correctly without overriding fully the user-agent.

what's the proper way to override the entire user-agent field? passing `[{"User-Agent", "foo"}]` in the `request` `header` position only append to hackney's user-agent. How can I tell hackney to use a diff user-agent?

## request

```elixir
iex(53)> HTTPoison.post "http://localhost:9990", "test", [{"User-Agent", "foobar"}], hackney: [headers: [{"User-Agent", "foo"}]]

```

## logged

```sh
± socat tcp-listen:9990,reuseaddr,fork -
POST / HTTP/1.1
Content-Type: application/octet-stream
User-Agent: hackney/1.6.6, foobar
Host: localhost:9990
Content-Length: 4

test


```

## expected
expected the user-agent to be overriden fully not appended to the hackney default ua

**Comment by edgurgel** [comment]
Hey @dweinstein, could you try updating hackney cause it had some issues merging headers recently.

**Comment by dweinstein** [comment]
@edgurgel seems like it did the trick, thanks! (I actually bumped httpoison to 0.11.1 and that worked itself out).

**Comment by edgurgel** [comment]
Awesome 👍
