### ISSUE TITLE
Problem get streaming from ip camera 

### ISSUE THREAD

**Issue by zentechnamhoang** [edgurgel/httpoison#254]
I have request video stream from ip camera FI9821P with url 
"http://kk3096.myfoscam.org:2000/cgi-bin/CGIStream.cgi?cmd=getMJStream&usr=test123&pwd=test123"

with `HTTPoison.get "http://kk3096.myfoscam.org:2000/cgi-bin/CGIStream.cgi?cmd=getMJStream&usr=test123&pwd=test123", [], [stream_to: self, async: :once]`
but the result is always bad request 
`%HTTPoison.Error{id: #Reference<0.0.2.2767>, reason: :bad_request}`
is this a bug ?

**Comment by ijunaid8989** [comment]
@zentechnamhoang  It would be slightly informative if you will mention your HTTPoison version as well.

**Comment by zentechnamhoang** [comment]
@ijunaid8989 Your HTTPoison version is 0.10.0

**Comment by ijunaid8989** [comment]
Have you tried with the latest version? as Its 0.11.2?

**Comment by ijunaid8989** [comment]
@zentechnamhoang on version 0.11.1
```
iex(2)> HTTPoison.get "http://kk3096.myfoscam.org:2000/cgi-bin/CGIStream.cgi?cmd=getMJStream&usr=test123&pwd=test123", [], [stream_to: self, async: :once]
The erlang-history file at /home/ijunaidfarooq/.erlang-hist.nonode@nohost was corrupted by DETS. An attempt to repair the file will be made, but if it fails, history will be ignored for the rest of this session. If the problem persists, please delete the history file (and maybe submit it with a bug report).
{:ok, %HTTPoison.AsyncResponse{id: #Reference<0.0.3.26783>}}
iex(3)> 
```

**Comment by ijunaid8989** [comment]
But Yeah after flush there is an error.
```
{:ok, %HTTPoison.AsyncResponse{id: #Reference<0.0.1.2774>}}
iex(3)> flush
%HTTPoison.Error{id: #Reference<0.0.1.2774>, reason: :bad_request}
:ok
iex(4)> 
```

**Comment by zentechnamhoang** [comment]
Yeah, this is my problem
