### ISSUE TITLE
the broken SSL issue is not a bug?

### ISSUE THREAD

**Issue by nhooyr** [edgurgel/httpoison#255]
https://github.com/edgurgel/httpoison/tree/39674d0f31b0a1a14b70a438649a41a787b1ca54#note-about-broken-ssl-in-erlang-19

In the thread linked, someone commented:

https://bugs.erlang.org/browse/ERL-192

**Comment by jonchoukroun** [comment]
I've been trying to solve this issue for a few days, running Erlang/OTP 20, Elixir 1.5.0, ex_aws 1.0, then several versions of either httpoison or hackney directly. All result in a handshake failure. But running the above linked test I get an `{:ok, ...}` response.

Back to the drawing board.

**Comment by nhooyr** [comment]
Going to close as it has been a long time and I'm not sure if this is relevant anymore.
