### ISSUE TITLE
Module  :unicode_util is not available

### ISSUE THREAD

**Issue by david-wilson** [edgurgel/httpoison#264]
OTP Version 19, Elixir 1.4.2, HTTPoison 0.11.1

Call `HTTPoison.get! "https://google.com"`.

Get:
```HTTPoison.get! "https://google.com"
** (UndefinedFunctionError) function :unicode_util.lowercase/1 is undefined (module
 :unicode_util is not available)
                :unicode_util.lowercase('google.com';)
         (idna) c:/Users/david/src/myapp/deps/idna/src/idna.erl:57: :idna.low
ercase_list/1
         (idna) c:/Users/david/src/myapp/deps/idna/src/idna.erl:10: :idna.to_
ascii/1
      (hackney) c:/Users/david/src/myapp/deps/hackney/src/hackney_url.erl:96:
 :hackney_url.normalize/2
      (hackney) c:/Users/david/src/myapp/deps/hackney/src/hackney.erl:291: :h
ackney.request/5
    (httpoison) lib/httpoison/base.ex:432: HTTPoison.Base.request/9
    (httpoison) lib/httpoison.ex:66: HTTPoison.request!/5
```

Tried changing Hackney to an older version after seeing some similar issues in their github issues:
`{:hackney, "~> 1.8.2", override: true},`

But no change.

**Comment by endrin** [comment]
The problem is with one of hackney dependencies, idna (ok, it's easy to see from stack trace), which depends on unicode_util_compat, which is actually broken. And also this problem is pretty hard to reproduce, it works on my Linux server, but yields same error on Windows laptop. Here's [related idna issue](https://github.com/benoitc/erlang-idna/issues/16).

**Comment by endrin** [comment]
I'm sorry, haven't checked this before, but rolling back to hackney 1.8.2 actually works. But you need to set its version as exact match, i.e use `==` instead of `~>`: `{:hackney, "== 1.8.2", override: true},` Otherwise, mix will always download latest 1.8.x version.

**Comment by 2c2c** [comment]
forcing 1.8.0 worked for me (1.8.2 did not).
