### ISSUE TITLE
HTTPoison can get into a state where all requests to a host:port give empty responses

### ISSUE THREAD

**Issue by SimonWoolf** [edgurgel/httpoison#268]
On a production app, HTTPoison occasionally seems to get into a state where every request made to a particular host:port results in `{:ok, %HTTPoison.Response{body: "", headers: [{"Date", "Fri, 23 Jun 2017 12:57:38 GMT"}, {"Content-Length", "0"}, {"Content-Type", "text/plain; charset=utf-8"}], status_code: 0}}`. (that was just a normal GET request, no streaming or anything).

The router logs for the server I'm making the request to claim that it does start, but is immediately cancelled by the client: `secs=0.000 cancelled=true`.

After a couple hours in that state, it seems to fix itself. If I connect with iex remotely, stopping and restarting the `:hackney` otp app fixes it (restarting the `:httpoison` app does not). (And making the same request that HTTPoison is making with curl, from the same container the elixir app is running in, works fine).

I only saw this happen after upgrading from hackney 1.4.10 / httpoison 0.8.0 to hackney 1.8.0 / httpoison 0.11.2, so possible that it's a regression, but hard to do any kind of bisection since I can't reproduce this locally at all. It happens with with latest httpoison and hackney 1.8.6.

Honestly I don't know whether this is a bug in httpoison, hackney, the router, the destination server, or my app. Can't see any relevant issues in hackney or httpoison -- given that restarting :hackney seems to fix it, I guess hackney seems more likely than httpoison. But I'm hoping you've seen something like this before and/or have some suggestions of some things that might cause it?

Many thanks in advance for any suggestions.

**Comment by edgurgel** [comment]
If I had to guess I would say this is more likely to be a hackney issue than an HTTPoison issue. It would be awesome to have a simple way to replicate :(

**Comment by SimonWoolf** [comment]
I no longer believe this is an httpoison or hackney problem. Ended up adding some tracing to hackney [right at the boundary](https://github.com/ably-forks/hackney/commit/9bb103c325c36bace75edebdde42a626c77e1994), to see what's actually coming over the wire (triggered by detecting the issue, just turns tracing on long enough to run one request then back off again, so it could be run in production, given I can't reproduce locally). And -- it does seem to genuinely be receiving a response over the wire which (invalidly) claims to have status code 0: `HTTP/1.1 000 status code 000\r\nDate: Wed, 19 Jul 2017 02:55:11 GMT\r\nContent-Length: 0\r\nContent-Type: text/plain; charset=utf-8\r\n\r\n`. Very weird. But means this isn't a client-side bug, so closing this issue.

**Comment by edgurgel** [comment]
Thanks for updating the issue, @SimonWoolf ! :)
