### ISSUE TITLE
iolists are supported as body, but @type body denies them 

### ISSUE THREAD

**Issue by ellispritchard** [edgurgel/httpoison#273]
The docs for `HTTPoison.Base.request/5` say body can be an iolist:

> Body:
        * binary, char list or an iolist
        * `{:form, [{K, V}, ...]}` - send a form url encoded
        * `{:file, "/path/to/file"}` - send a file
        * `{:stream, enumerable}` - lazily send a stream of binaries/charlists

But `body` type is defined as:

```
      @type body :: binary | {:form, [{atom, any}]} | {:file, binary}
```

which gives Dialyzer errors when you use an iolist.

**Comment by edgurgel** [comment]
Could you try with the latest 0.13?

**Comment by ellispritchard** [comment]
Thanks, that does make the Dialyzer issue go away, but...

I note that you are now using `any` for the type of the body param in almost all circumstances, instead of the `body` type, which is unchanged and only used as result of the `process_request_body/1` hook and body param of `HTTPoison.Base.request/9` - I'm worried that might cause problems later (or with other code)?

e.g. `process_request_body/1` can now take anything as an argument, but according to the typing must still return `body`type which is still just the original types, excluding an 'iolist'?

Would an alternative fix be to extend the `body` type to include `maybe_improper_list`, and put all the `body` type-specs for the body parameter back? This would have the advantage of actually documenting in code the types the body actually supports (especially if aliasing the type to `iolist`).
