### ISSUE TITLE
Is HTTPoison.start always required?

### ISSUE THREAD

**Issue by rvignesh89** [edgurgel/httpoison#274]
This sounds a simple question but I'm quite new to Elixir so still figuring out how things work.

In your usage example you start httpoison before making any requests. The start function merely ensures dependencies are loaded. Do we need to call start before making any request? I'm using httpoison in a phoenix application. Doesn't it suffice if I include httpoison in my application dependency in mix.exs?

The reason I'm asking is because I plan to send requests inside elixir tasks. Having to start before making any request feels like there might be some dependency between multiple requests. Even though I know that global state is not common in functional languages like Elixir just wanted to clarify things beforehand!

I was more confused because I noticed httpoison being started before making requests in [this](https://github.com/C404/distance-matrix-api/blob/master/lib/distance_matrix_api.ex#L45) lib.

**Comment by edgurgel** [comment]
if you have an elixir application you just need to add to the  mix.exs `applications` list. If you are using Elixir 1.4 you probably don't even need to add anything apart from the dependency.

Mix tasks are a bit difference, this stackoverflow link may help you: https://stackoverflow.com/questions/35706320/starting-mix-task-process-dependencies
