### ISSUE TITLE
Poorly formatted error

### ISSUE THREAD

**Issue by Hajto** [edgurgel/httpoison#281]
Calling get on `http://www.erlang.se/` causes `{:error, {:poorly_formatted_size, '39 '}}`.

Can I do anything about it?

**Comment by edgurgel** [comment]
Hey, can you specify exactly what call you are doing? e.g `HTTPoison.get....` ?

**Comment by edgurgel** [comment]
Ok doing a `curl` request I noticed that no content-length is returned from `erlang.se` so I suspect hackney is not liking it 🤔

**Comment by nashby** [comment]
Looks like it was fixed in Hackney https://github.com/benoitc/hackney/pull/450 (it's not released yet though). I think we can close this @edgurgel

**Comment by edgurgel** [comment]
Awesome ! Thanks for the update :)
