### ISSUE TITLE
Support for DELETE bodies

### ISSUE THREAD

**Issue by coryodaniel** [edgurgel/httpoison#284]
I don't know if this is controversial, but Ive needed `DELETE` with a body for a few different APIs I have consumed and since it's not explicitly excluded from the [HTTP spec](https://tools.ietf.org/html/rfc2616#section-9.7) was considering submitting a PR.

With the optional values (`headers`, `options`) and the ability for `headers` to be a map using the method signatures to keep the API consistent becomes ambiguous...

```elixir
# As it exists
@spec delete(binary, headers, Keyword.t) :: {:ok, Response.t | AsyncResponse.t} | {:error, Error.t}
def delete(url, headers \\ [], options \\ [])

# Adding this signature creates a compiler error due to default conflicts.
@spec delete(binary, any, headers, Keyword.t) :: {:ok, Response.t | AsyncResponse.t} | {:error, Error.t}
def delete(url, body, headers \\ [], options \\ [])
```

`post/2` gets around this by making the body required, which would probably be annoying for the 99% of delete use cases and not be consistent with the current API. I was curious if this functionality would be useful to add for others, and if so which of the following approaches makes most sense?

Adding a new function for handling deletes with bodies `delete_with_body/4`
```elixir
# Seems a little on the nose.
@spec delete_with_body(binary, any, headers, Keyword.t) :: {:ok, Response.t | AsyncResponse.t} | {:error, Error.t}
def delete_with_body(url, body, headers \\ [], options \\ [])
```

Or adding `delete/1` and `delete/4` and making the body required (type `any`).
```elixir
@spec delete(binary) :: {:ok, Response.t | AsyncResponse.t} | {:error, Error.t}
def delete(url)
@spec delete(binary, any, headers, Keyword.t) :: {:ok, Response.t | AsyncResponse.t} | {:error, Error.t}
def delete(url, body, headers \\ [], options \\ [])
```

Two APIs that use `DELETE` bodies I've encountered recently:
* [Kubernetes](https://kubernetes.io/docs/api-reference/v1.5/#delete-7)
* [Stripe](https://stripe.com/docs/api#cancel_subscription)

**Comment by edgurgel** [comment]
I wouldn't add this change just because you can just `request`/`request!` and passing any verb, body, header. Unless we have more people asking for this...

**Comment by mtarnovan** [comment]
I needed this too when implementing API clients, having to fall back to `request` for `DELETE` makes my code awkward.

**Comment by rupurt** [comment]
It's super confusing there is no `delete/4`. Body params are allowed as part of the HTTP spec.

**Comment by edgurgel** [comment]
Let's do this then! We just need to ensure that previous usage of delete won't be affected?

**Comment by brettwise** [comment]
+1. FYI, ran into this today @edgurgel. 

Had to drop down and use `request` to complete a request. Not a huge deal but the expectation was that it would be there. And the stack trace did not seem very helpful for what was going on and took me a few minutes to realize it was because `HTTPoison.delete` did not support calls with a body.

Came up while using the Auth0 API which expects some `DELETE` requests to be made with a body.

**Comment by edgurgel** [comment]
A delete with a body is something that was considered wrong and just recently it has been allowed but without a defined semantic : https://stackoverflow.com/a/10015724/1544452

If someone needs to send a delete with a body they can use request/5 or request/1

If we have a new major version we can consider adding body as an argument to delete down the line but I don't think it's worth the breaking change now. 

Thanks, everyone
