### ISSUE TITLE
GET request sends body with literal empty string ("\"\"") not actual empty body

### ISSUE THREAD

**Issue by samphilipd** [edgurgel/httpoison#285]
It seems that HTTPoison is sending two literal quotation marks as the request body for GET requests, rather than an actual empty body.

This causes problems accessing certain APIs which expect a body to be parseable if present.

For example, we are accessing the Close.IO API like this:

```elixir
defmodule MyClient do
  use HTTPoison.Base

  def find_leads(search_term) do
    get("/lead/", [], params: %{query: search_term})
  end
end
```

The recorded VCR cassette looks like this:

```json
[
  {
    "request": {
      "body": "\"\"",
      "headers": {
        "Accept": "application/json"
      },
      "method": "get",
      "options": {
        "basic_auth": [
          "<REDACTED>",
          ""
        ]
      },
      "request_body": "",
      "url": "https://app.close.io/api/v1/lead/lead_foobar/?"
    },
    "response": {
      "body": "{\"error\": \"Please send valid JSON with a 'Content-Type: application/json' header.\"}",
      "headers": {
        "Content-Type": "application/json",
        "Date": "Sun, 03 Sep 2017 14:08:04 GMT",
        "Set-Cookie": "session=; Expires=Thu, 01-Jan-1970 00:00:00 GMT; Max-Age=0; Path=/",
        "Strict-Transport-Security": "max-age=31536000; includeSubDomains",
        "Vary": "Accept",
        "X-Frame-Options": "SAMEORIGIN",
        "X-Rate-Limit-Limit": "600",
        "X-Rate-Limit-Remaining": "599",
        "X-Rate-Limit-Reset": "14",
        "Content-Length": "83",
        "Connection": "keep-alive"
      },
      "status_code": 400,
      "type": "ok"
    }
  }
]
```

There is a body present in the request, I would like to instead send the GET request with no body at all.

**Comment by edgurgel** [comment]
🤔 Hmmm that's really weird...

**Comment by samphilipd** [comment]
It also seems to serialize a `nil` body to an actual `"null"` string which is even more worrying. I wonder if there is some JSON serialization going on somewhere that shouldn't be?

**Comment by samphilipd** [comment]
@edgurgel Any updates on this? We're still seeing this issue.

**Comment by edgurgel** [comment]
I don't know how to replicate this issue. Feel free to send a PR fixing the issue 👍

**Comment by samphilipd** [comment]
@edgurgel You can chalk this one up to user error - I just realised we were overriding `process_request_body` to encode to JSON ** facepalm **.
