### ISSUE TITLE
Body to string

### ISSUE THREAD

**Issue by xnog** [edgurgel/httpoison#287]
How can I convert a binary body to string? I found the code below, but is there an easier way to do it?

```
  def raw_binary_to_string(raw) do
    Enum.reduce(String.codepoints(raw), fn(w, result) ->
      cond do
        String.valid?(w) ->
          result <> w
        true ->
          << parsed :: 8>> = w
          result <> << parsed :: utf8 >>
      end
    end)
```

Thanks

**Comment by edgurgel** [comment]
I would probably look for documentation around String and binaries and/or reach here https://elixirforum.com for questions. It may be possible that your question has an answer there already.

I'm closing the issue as it's not related to HTTPoison itself.
