### ISSUE TITLE
404 when making GET requests

### ISSUE THREAD

**Issue by caalberts** [edgurgel/httpoison#290]
I'm using HTTPoison to make a GET request to a website. It was working well previously and I was able to get 200 responses. However recently I started getting 404s. When I use CURL to the same URL, I'm able to get a 200 response.

Could someone help me point to what could have gone wrong?

**Comment by blackfist** [comment]
What's the url? You didn't really provide a lot of information to go on.

**Comment by caalberts** [comment]
I've not encountered this anymore.
