### ISSUE TITLE
Distinction between the two timeouts

### ISSUE THREAD

**Issue by Dzol** [edgurgel/httpoison#299]
I read the various issues here around timeouts but none explain the difference between the two that are [documented](https://hexdocs.pm/httpoison/HTTPoison.html#request/5). What exactly do the `timeout` and `recv_timeout` options mean? I'm guessing the following:

- `timeout` to establish (open) a TCP connection
- `recv_timeout` to receive an HTTP response having sent a request

The documentation says "timeout used when receiving a connection" for the `recv_timeout` but I wouldn't say we receive a connection as a client 😕 Is the guess above right?

**Comment by edgurgel** [comment]
Oh hey! Yes, it's confusing. Take a look at this issue and it may help clarify things: https://github.com/edgurgel/httpoison/issues/215

**Comment by Dzol** [comment]
Hey 🙂

I dug into Hackney... its connect_timeout _is_ about TCP session establishment and the recv_timeout is about HTTP response time. I'll get the source references together and post a PR with a description in documentation in the coming week.

How does that sound?

**Comment by edgurgel** [comment]
That would be great 👍

**Comment by Dzol** [comment]
Hey @edgurgel,

Thanks for your patience. I opened a small PR.

Do you have some suggestions on the phrasing that would make the details even more clear.

**Comment by edgurgel** [comment]
Awesome thanks!
