### ISSUE TITLE
it does not work with HTTP Status 204

### ISSUE THREAD

**Issue by Yamilquery** [edgurgel/httpoison#301]
I'm working in a Elixir module using httpoison.

So I make a request and I get a Status 204 (Not content), then httposion give me the next error:

```
1) Openpay.CardTest: failure on setup_all callback, test invalidated
     ** (Poison.SyntaxError) Unexpected end of input at position 0
     stacktrace:
       lib/poison/parser.ex:55: Poison.Parser.parse!/2
       lib/poison.ex:83: Poison.decode!/2
       (httpoison) lib/httpoison/base.ex:478: HTTPoison.Base.response/7
       (openpay) lib/openpay.ex:119: Openpay.make_request_with_key/6
       test/openpay/card_test.exs:38: anonymous fn/2 in Openpay.CardTest.__ex_unit_setup_all_0/1
       (ex_unit) lib/ex_unit/on_exit_handler.ex:98: ExUnit.OnExitHandler.exec_callback/1
       (ex_unit) lib/ex_unit/on_exit_handler.ex:82: ExUnit.OnExitHandler.on_exit_runner_loop/0
```

**Comment by Yamilquery** [comment]
The problem was in my client's api, therefore I close this issue.

**Comment by edgurgel** [comment]
That's strange 🤔 Did you find the reason why your tests were failing? It seems to be related with JSON decoding of the response

**Comment by acgourley** [comment]
I have a similar problem - I suspect my API end point isn't giving me valid JSON in response. Is there an option of getting back the raw response before poison gets a crack at it?

**Comment by acgourley** [comment]
Like me, the OP was probably using the example code which has: 
```
  def process_response_body(body) do
   parsed = body
   |> Poison.decode!
  end
```
Perhaps if the example was updated to have error handling this would be less likely.
