### ISSUE TITLE
Use http_proxy env variable

### ISSUE THREAD

**Issue by amencarini** [edgurgel/httpoison#305]
Hi! We're considering adopting linkerd in our infrastructure and was doing some research when I stumbled on this bit of documentation (https://linkerd.io/features/http-proxy/)

<img width="758" alt="screen shot 2017-12-28 at 09 36 10" src="https://user-images.githubusercontent.com/1100003/34406757-92589e94-ebb2-11e7-82d4-3b10b7050fe5.png">

We make ample use of httpoison in our code and I was wondering what's your opinion on having the httpoison code picking up on `http_proxy` env var automatically, if set.

**Comment by edgurgel** [comment]
I think that would be fine 👍 Do you mind sending a PR?

**Comment by amencarini** [comment]
Hi, opened a PR. It feels like it's doing a lot of stuff and feedback is greatly appreciated. I'm also not 100% sure about how to test if performance of this is ok.
