### ISSUE TITLE
Update Hackney version to 1.10.x or lower

### ISSUE THREAD

**Issue by jknipp** [edgurgel/httpoison#310]
Hackney version 1.11.0 introduces a breaking change that returns an empty response body when both the Content-Length and Transfer-Encoding headers are omitted. Until the fix is place the Hackney version should be pinned so that users don't accidentally get the newest Hackney version.

It was non-trivial to track down at least for me as most of my tests passed, but it was only when a particular service was accessed that the bug presented itself.
 
https://github.com/benoitc/hackney/issues/475

**Comment by axelson** [comment]
For reference that bug is now fixed in Hackney 1.12.0

https://github.com/benoitc/hackney/commits/1.12.0
https://github.com/benoitc/hackney/pull/496

**Comment by ijunaid8989** [comment]
In HTTPoison the Hackney version is lower than the latest. how can we update it to latest one? 1.15.1

**Comment by edgurgel** [comment]
@ijunaid8989 you should be able to simply run `mix deps.update hackney`. It should accept `>= 1.8` and `< 2.0`

**Comment by colinta** [comment]
Note for other people landing here: I'm using httpoison 1.5.1 and the version of hackney that is installed is 1.11.0, and this "empty request body" bug is biting me.  Running `mix deps.update hackney` had no affect until I included `hackney` as a dependency in mix.exs.
