### ISSUE TITLE
Timeouts cause all workers to timeout repeatedly

### ISSUE THREAD

**Issue by vfsoraki** [edgurgel/httpoison#313]
I set `recv_timeout` and `timeout` to `500` for my calls. I do not use a pool, but I suppose it uses default pool (or not?).

I call a webservice, which times out from time to time, and I have no problem with it. I just want to know when it does, and `HTTPosion` should give me this.

When a series of timeouts happen, I see that suddenly all my workers receive timeout error repeatedly. It seems that all my connections just time out instantly.

I have to stop my app, wait a bit (like 10 seconds) and then start it again for workers to behave normally.

I had to switch to `HTTPotion` to be able to keep production running, and I see no problem with `HTTPotion`.

I don't know really if this is something that is related to this library or something else, but I saw #64 but I suppose that is fixed now.

I was using version `0.11.2`.

**Comment by vfsoraki** [comment]
Maybe write why?

Is this how you support your package?

I'm happy I switched, and my problem is solved after the switch.

**Comment by edgurgel** [comment]
Isn't this a duplicate of https://github.com/edgurgel/httpoison/issues/314 ?
