### ISSUE TITLE
hackney not compiling due to rebar_abort.

### ISSUE THREAD

**Issue by elbow-jason** [edgurgel/httpoison#32]
When compiling HTTPoison I'm getting this error:

```
==> hackney (compile)
Compiling src/hackney_connect/hackney_http_connect.erl failed:
src/hackney_connect/hackney_http_connect.erl:11: can't find include lib "kernel/src/inet_dns.hrl"
ERROR: compile failed while processing /home/elbow/elixir-sips-progress/issues/deps/hackney: rebar_abort
** (Mix) Could not compile dependency hackney, /home/elbow/.mix/rebar command failed. If you want to recompile this dependency, please run: mix deps.compile hackney
```

While I realize this is likely not an issue with HTTPoison's source this does make this dependency unusable (at least for me).

I'm using ```{ :httpoison, "~> 0.5" }``` and Elixir 1.0.2.

**Comment by elbow-jason** [comment]
Apparently I was  **missing erlang-src**. I installed erlang-src and everything works fine. Sorry for the issue.  :)

**Comment by edgurgel** [comment]
No problem! Hope everything runs fine for you now!

**Comment by tiagodavi** [comment]
I have the same error even after to install erlang-src.

**Comment by tiagodavi** [comment]
I'm sorry, I have just solved only updating the HTTPoison.

**Comment by wsmoak** [comment]
Just ran into this in a project that has been working fine for weeks... I'm trying to track down what may have changed.

**Comment by edgurgel** [comment]
Could you check which version of rebar is in your PATH? I'm afraid this is a really old rebar version coming from old packages.
