### ISSUE TITLE
Add behaviours to allow for mox'ing

### ISSUE THREAD

**Issue by bcardarella** [edgurgel/httpoison#329]
Using the library [mox](https://github.com/plataformatec/mox) to write mocks I find myself always writing a wrapper module for HTTPoison that ends up being a simple pass-thru. It would be great if HTTPoison has behaviours defined to allow override directly rather than having to create the pass-thru modules in mocking.

**Comment by edgurgel** [comment]
Do you mean something like this https://github.com/edgurgel/httpehaviour ?

**Comment by bcardarella** [comment]
A quick look over, this could satisfy my concern. But is it prod ready?  I see it only had a single non-readme commit and is over three years old... is it actively used still?

**Comment by edgurgel** [comment]
Tthis was just an idea on how we could evolve HTTPoison to be based on behaviours. I'm not sure how we could achieve what you need with the current existing implementation 🤔

**Comment by JosephMichaelWebb** [comment]
Hello @bcardarella and @edgurgel , I made a PR (https://github.com/edgurgel/httpoison/pull/330) that should allow using mox without a wrapper module. Please take a look. Any feedback you have would be greatly appreciated.
