### ISSUE TITLE
timeout seems to be divided by 10

### ISSUE THREAD

**Issue by dlameri** [edgurgel/httpoison#338]
Today i noticed that all my calls to an external service had a maximum 30ms response time, which is really odd since this service isn't that fast.

After some digging i saw that my recv_timeout was configured to 300, so i tried to change it to 400 and then my graph changed the max to 40ms.

I debugged my measuring and it seems to be working ok.

Is it possible that the recv_timeout is in microseconds, not in miliseconds?

**Comment by edgurgel** [comment]
I'm pretty sure it's milliseconds. Maybe you are having trouble setting up the connection? 

You will see these tests pass if you add this to `httpoison_test.exs`:

```elixir
  test "timeout" do
    response = HTTPoison.get("localhost:8080/delay/5", [], recv_timeout: 5_100)
    assert {:ok, %HTTPoison.Response{}} = response

    response = HTTPoison.get("localhost:8080/delay/5", [], recv_timeout: 4_900)
    assert {:error, %HTTPoison.Error{id: nil, reason: :timeout}}
  end

```

**Comment by edgurgel** [comment]
hey I'm closing this issue but feel free to reopen if you can confirm that there's an issue
