### ISSUE TITLE
Request state variable

### ISSUE THREAD

**Issue by yrashk** [edgurgel/httpoison#34]
It would be great to pass an (optional?) state variable through process_ handlers, for complicated request processes.

**Comment by edgurgel** [comment]
I'm thinking on something like this:

If you are interested in passing around a state variable, you provide a tuple as result on `process_request_headers` like this:

```elixir
defp process_headers(headers) do
  {headers, state}
end
```

Then on `process_response_body`

```elixir
defp process_response_body(body, state \\ nil) do
#...
end
```
I still need to check how `defoverridable` works with default arguments.

I wonder if it's useful just for the process_ functions that act on the response.

**Comment by maca** [comment]
+1 I would like have the request body signed using HMAC in a custom header, I have no access to the request body in the proces_headers function.

**Comment by edgurgel** [comment]
I will send a PR tomorrow with my proposal. It won't break the API and it will do the job.

**Comment by edgurgel** [comment]
I just released [HTTPehaviour](https://github.com/edgurgel/httpehaviour). It should make it easier for these cases where the user needs to use different parts of the request to take some action.

**Comment by wpcarro** [comment]
Where did this land? Does anyone have a preferred pattern for signing requests with hmacs, etc? I feel like this is a valid use-case to support a stateful `callback` API, but I'm open to alternative design patterns if anyone is willing to share their preferred methods.
