### ISSUE TITLE
localhost URI invalid URL ?

### ISSUE THREAD

**Issue by alduro** [edgurgel/httpoison#341]
Hi. I'm doing some tests locally posting to `http://localhost:3121` url and getting invalid URL. How should I deal with this ? Thanks.

**Comment by edgurgel** [comment]
Can you please show how the error looks like? If you check `httpoison` tests you can see that we also use http://localhost in multiple places and it seems to be working just fine.

```
iex(1)> HTTPoison.get!("http://localhost:9200")
%HTTPoison.Response{body: "{\n  \"name\" : \"Chondu the Mystic\",\n  \"cluster_name\" : \"elasticsearch\",\n  \"version\" : {\n    \"number\" : \"2.1.2\",\n    \"build_hash\" : \"63c285e4741baf609e963cb9d463ad1a47e1a179\",\n    \"build_timestamp\" : \"2016-01-27T12:57:52Z\",\n    \"build_snapshot\" : false,\n    \"lucene_version\" : \"5.3.1\"\n  },\n  \"tagline\" : \"You Know, for Search\"\n}\n",
 headers: [{"Content-Type", "application/json; charset=UTF-8"},
  {"Content-Length", "326"}], request_url: "http://localhost:9200",
 status_code: 200}
```

**Comment by alduro** [comment]
It turned out that If I pass the entire URL like `http://localhost:5121/logout` the final url for `get`ahd the domain duplicated so I had to user a `process_url` first and then add the `/logout` part and did work. Thanks and sorry for the delay in answering.

**Comment by edgurgel** [comment]
@alduro all good! Glad you found the issue!
