### ISSUE TITLE
HTTPPoison.Base process_response_body with maybe gziped headers

### ISSUE THREAD

**Issue by favetelinguis** [edgurgel/httpoison#345]
Is there a way one can check the headers if the message is gziped in:

`defp process_response_body(body), do: body`

in my case i can not assume they are always gziped so I need to check the response headers if its gziped or not but I cant figure out how to do this with HTTPPoison.Base?

**Comment by steffkes** [comment]
I had a similar case and i'd say it's not possible. `response` calls those `process_*` functions only with a single argument: 

https://github.com/edgurgel/httpoison/blob/5cfb016f5683117be48a77704d11d47c43c42021/lib/httpoison/base.ex#L703-L708

which means, you have either access to `headers` or `body` but not both. @edgurgel i'd guess that's basically just what was existing back then (i've traced it back to a commit from three years ago). i can't say w/o further looking how much of a change that would be, if:

We setup the `Response` and then pass it through one/some function(s) which would be allowed to transform the complete response? In that case, one could execute conditional stuff, like @favetelinguis asked for and for example decode json only if the `content-type` says so.

Same would be true for the `Request`. Wouldn't be the first time i'd like to have conditional encoding of the request body depending on the headers.

**Comment by ryanwinchester** [comment]
You should be able to use `process_response/1` now in `master`. It is the last thing called on the response and if you have one piece that depends on another, is probably the best thing to use for that currently.

```elixir
defmodule MyThing do
  use HTTPoison.Base

  alias HTTPoison.Response

  def process_response(response) do
    %Response{response |
      body: body_processor(response.headers, response.body)
    }
  end

  # contrived example
  defp body_processor(headers, body) do
    if headers, do: body, else: ""
  end
end
```
