### ISSUE TITLE
Support multipart response parsing

### ISSUE THREAD

**Issue by dnlserrano** [edgurgel/httpoison#346]
Hi there fellow Elixir sippers,

Thanks so much for the HTTPoison lib @edgurgel and contributors! ❤️ 

Recently, I stumbled upon an issue regarding `Content-Type` `multipart/mixed`. I was trying to get the response of a Python service that uses multipart to return JSON, image pairs. Unfortunately, `httpoison` does not support this out of the box (which I understand might be by design).

The [`hackney`](https://github.com/benoitc/hackney/) library seems to support it though, via [`hackney_multipart`](https://github.com/benoitc/hackney/blob/master/doc/hackney_multipart.md). ❤️ 💚 💙 💛 💜 

That's what I ended up using in my Elixir code.

Anyway, I was wondering if adding support for parsing a multipart response body was something you guys would feel as a good plus to this library. I've noticed so far you've wanted to keep it fairly simple and plug-and-play-like (with functions like `process_response_body/1` available.

I have created a [simple Sinatra server](https://github.com/dnlserrano/multipart-example/blob/master/app.rb) (Ruby, sorry 🙈) with a multipart response to test this. I'll soon open the simple PR to add multipart support.

Let me know what you think. Thanks! 😄

**Comment by dnlserrano** [comment]
AFAIU, my proposed changes (PR #347) introduce a breaking change. You might not even want this functionality in the lib (understandable). Even if that's the case, this might be useful for some people that want to tackle multipart with HTTPoison and/or hackney. 😊 

We could add the functionality via a flag/version bump? I'll wait for your feedback. Thanks!

**Comment by edgurgel** [comment]
Hey @dnlserrano, thanks for creating this issue and sending a PR. I'm pretty sure we can find a way to introduce this change! I will review this later today/tomorrow! 

I love Sinatra btw! I would probably add a new multipart endpoint to [httparrot](https://github.com/edgurgel/httparrot) so that we have also an integration test actually running the request.
