### ISSUE TITLE
Option for Httpoison and Hackney to not append library headers

### ISSUE THREAD

**Issue by yuchunc** [edgurgel/httpoison#352]
Hi,

A third party API is very strict about request headers, it allows nothing but the ones documented. I’m using HTTPoison as REST client, but Hackney adds some header information, and the third party service would error. Is there some options I can set to disable this behaviour on Hackney? Or do I have to override the library module?

Thank you!

**Comment by edgurgel** [comment]
Hey @yuchunc, could you explain exactly which headers are being appended?

**Comment by yuchunc** [comment]
Hi @edgurgel, these are the headers that were added
```
["host", "user-agent", "content-type", "content-length"]
```

I have also opened an issue on Hackney's side https://github.com/benoitc/hackney/issues/529, I'm gonna try to see if I can submit my first ever erlang PR to patch this. :)

**Comment by yuchunc** [comment]
Closing because it's Hackney's issue.
