### ISSUE TITLE
Pass URL query parameters

### ISSUE THREAD

**Issue by aidylewis** [edgurgel/httpoison#376]
Is it possible to pass post URL parameters with HTTPoison as I would do with Curl.

```
curl -i -XPOST http://localhost:8086/query --data-urlencode "q=CREATE DATABASE mydb"

**Comment by aidylewis** [comment]
HTTPoison.post "http://localhost:8086/query", "", [{"Content-Type", "application/x-www-form-urlencoded"}],  params: %{q: "CREATE DATABASE mydb"}

**Comment by edgurgel** [comment]
I wonder if using "{:form" as body would have done the job: https://github.com/benoitc/hackney#send-a-body ? Like this https://github.com/edgurgel/httpoison/blob/da4187882649b4d14a3d57f1e3d732a6c98443e7/test/httpoison_test.exs#L57-L59 ?
