### ISSUE TITLE
Telemetry support

### ISSUE THREAD

**Issue by steffenix** [edgurgel/httpoison#383]
Are you planning to add telemetry support to the library? I can help with a PR.
Maybe it should be added in hackney.

**Comment by edgurgel** [comment]
Great question! I think we should do this inside hackney. 

I know that hackney uses [`erlang-metrics`](https://github.com/benoitc/metrics) as interface so two options (I think?):

* Replace `erlang-metrics` with telemetry
* Implement a backend for `erlang-metrics` with telemetry ?

**Comment by steffenix** [comment]
`erlang-metrics` and `hackney` being the same creator, I think it's up to him to see if he wants to migrate to `telemetry` and have apps with `erlang-metrics` migrating to `telemetry` as well.

If we are not implementing this into httpoison this discussion should be in https://github.com/benoitc/hackney and could be closed.

**Comment by PhillippOhlandt** [comment]
I would love telemetry support. Right now, I have a use case where I want to be notified after every request with all the request and response infos.

**Comment by steffenix** [comment]
What I have did now is a lib that I used on top of httpoison where I have added my telemetry metrics.

**Comment by binaryseed** [comment]
Any further thoughts on this? It'd be nice to get `telemetry` integrated somewhere :)

Ideally, we'd follow the recommendations for submitting `start`, `stop` and `failure` spans, which will enable tracing as well as metrics collection...

**Comment by GregMefford** [comment]
Just stopping by to say that I'm also interested - I agree that it would be useful to get it added in Hackney itself, but that doesn't preclude HTTPoison also adding it, so that we get it one way or the other. 😉

**Comment by 3fernandez** [comment]
Hi there! 🙂

I'm working on an XML tool that leverages `use HTTPoison.Base`, and I'm trying to instrument it using `use NewRelic.Tracer`. But I don't see how the pieces should fit together. Any advices or tips?

 Thanks

**Comment by zoidbergwill** [comment]
@3fernandez I think we wanna emit start/stop/failure events, like @binaryseed mentioned, sort of like ```:telemetry.execute([:ecto, :repo, :init], %{system_time: System.system_time()}, %{repo: repo, opts: opts})``` from [here](https://hexdocs.pm/phoenix/telemetry.html#an-ecto-example), but in [`lib/httpoison/base.ex`](https://github.com/edgurgel/httpoison/blob/master/lib/httpoison/base.ex), where instead of `repo` and `opts` we'd send some information about the request, maybe some of these fields from `opentelemetry_phoenix` could work as inspiration [here](https://github.com/opentelemetry-beam/opentelemetry_phoenix/blob/main/lib/opentelemetry_phoenix.ex#L107-L119)

**Comment by zoidbergwill** [comment]
The [upstream hackney ticket](https://github.com/benoitc/hackney/issues/585) is still open, so I think this one is still unsolved too?

**Comment by steffenix** [comment]
I am closing long opened issues on my account to make some cleanup.

**Comment by zoidbergwill** [comment]
I think it'd be great to track this feature request for httpoison, and track the upstream hackney ticket.

Would I need to make my own ticket that is a dupe of this closed ticket be the ideal solution for you?

**Comment by steffenix** [comment]
Yes sure.

**Comment by edgurgel** [comment]
https://medium.com/the-realreal-product-tech-blog/monitoring-hackney-connection-pools-with-telemetry-3aaeafa8eeb8
