### ISSUE TITLE
Econnrefused error

### ISSUE THREAD

**Issue by paulrusu8** [edgurgel/httpoison#386]
I am getting the {:error, %HTTPoison.Error{id: nil, reason: :econnrefused}-error  and was wondering what the reason for and the solution of it are.

P.S.: It seems that this error is very common as it is appearing in the usage examples!!!

**Comment by edgurgel** [comment]
It means that the connection was refused. The port is probably not open?

**Comment by matheuscamarques** [comment]
i have similar error 
https://elixir-lang.slack.com/files/U03SBN4FCHY/F03SE5FUFAB/image.png
