### ISSUE TITLE
Under which conditions will {:ok, response} be returned? What status codes are considered as "successful"?

### ISSUE THREAD

**Issue by redsalmon91** [edgurgel/httpoison#388]
Hi there,

Recently I have observed that `HTTPoison.post` would return `{:ok, response}` even for status code of 404. Is this a bug or by design? I could not find the definition of a successful request in the documentation.

Thanks!

**Comment by edgurgel** [comment]
@redsalmon91, that's a great question and I think we should have docs around this.

`{:ok ,response}` means that the HTTP server replied with something valid. There was no error while getting the HTTP response. 

The response will have the status that was replied, the body and the headers. Success of the actual response is defined by the user of HTTPoison.

**Comment by redsalmon91** [comment]
@edgurgel Thanks for the information!
