### ISSUE TITLE
HTTPoison not starting automatically on Elixir 1.8.1 when mix project is started with --sup

### ISSUE THREAD

**Issue by vamsiikrishna** [edgurgel/httpoison#389]
I  bootstrapped a project with mix and used the --sup flag.

Without using ```HTTPoison.start``` before using the module functions , I am getting the following error 

```
** (ArgumentError) argument error
    (stdlib) :ets.lookup_element(:hackney_config, :mod_metrics, 2)
    /Users/v/code/elixir/utils/deps/hackney/src/hackney_metrics.erl:27: :hackney_metrics.get_engine/0
    /Users/v/code/elixir/utils/deps/hackney/src/hackney_connect.erl:78: :hackney_connect.create_connection/5
    /Users/v/code/elixir/utils/deps/hackney/src/hackney_connect.erl:47: :hackney_connect.connect/5
    /Users/v/code/elixir/utils/deps/hackney/src/hackney.erl:330: :hackney.request/5
    lib/httpoison/base.ex:786: HTTPoison.Base.request/6
    (utils) lib/Proj/uploader.ex:7: Proj.Uploader.upload_file/4

```

This will be solved if I just use ```HTTPoison.start``` before using HTTPoison functions.

Also the issue was solved if ```:httpoison``` was added to the ```extra_applications``` list
```
  def application do
    [
      extra_applications: [:logger, :httpoison],
    ]
  end
```

Are there any other ways to solve it ?  Should the docs be updated to instruct the users to register ```:httpoison``` if they had bootstrapped their application with ``` --sup ``` option ?

Thanks !

**Comment by edgurgel** [comment]
Hey @vamsiikrishna, I've just installed Elixir 1.8.1 and I couldn't replicate the issue. Could you provide some way for me to pull the source that you are using (or a simplified version of it?). Maybe an example github repo?
