### ISSUE TITLE
"Codepoint 95 not allowed" is too restrictive

### ISSUE THREAD

**Issue by Slumber86** [edgurgel/httpoison#390]
When try to call an url with underscore hakney return this error: `"Codepoint 95 not allowed (\'DISALLOWED\') at posion XX`

This is already fixed in hackney 1.15.1 https://github.com/benoitc/hackney/issues/557, is it possible to update the dependancy?

**Comment by edgurgel** [comment]
@Slumber86 you should be able to `mix deps.update hackney`. HTTPoison uses `~> 1.8` which will allow you to update to anything less than `2.0`.

**Comment by edgurgel** [comment]
if this doesn't work feel free to reopen the issue!
