### ISSUE TITLE
how to access information on error?

### ISSUE THREAD

**Issue by 9mm** [edgurgel/httpoison#391]
how do i get more information about why a connection failed other than just the 'reason'. how can i get the response code, body, headers, etc.

My `case do` pattern match on a `.get()` is:

      {:error, error = %HTTPoison.Error{reason: reason}} ->
        # access headers etc?

**Comment by edgurgel** [comment]
If there was an error, there is no response. Kinds of errors are: "failed to connect", "domain name is invalid", etc

Anything that comes properly from the HTTP server will be handled as `{:ok, response}` no matter what is the code/header/body. Success is defined by the user.

**Comment by 9mm** [comment]
Ok, makes sense, thanks. What would be some of the reasons for a `:closed` error?

**Comment by edgurgel** [comment]
It means that the connection was closed by the server
