### ISSUE TITLE
Need to explicitly call HTTPoison.start() in mix tasks

### ISSUE THREAD

**Issue by StasD** [edgurgel/httpoison#402]
Hello,

I just found that I need to call `HTTPoison.start()` explicitly if I run the code which uses HTTPoison functionality from within custom mix tasks (see e.g. [this article](https://joeyates.info/2015/07/25/create-a-mix-task-for-an-elixir-project/))

I'm getting this error if I don't call `HTTPoison.start()`:

```
(ArgumentError) argument error
    (stdlib) :ets.lookup_element(:hackney_config, :mod_metrics, 2)
    /Users/myname/Projects/elixir/myapp/deps/hackney/src/hackney_metrics.erl:26: :hackney_metrics.get_engine/0
    /Users/myname/Projects/elixir/myapp/deps/hackney/src/hackney_connect.erl:78: :hackney_connect.create_connection/5
    /Users/myname/Projects/elixir/myapp/deps/hackney/src/hackney_connect.erl:47: :hackney_connect.connect/5
    /Users/myname/Projects/elixir/myapp/deps/hackney/src/hackney.erl:333: :hackney.request/5
    lib/ex_aws/request/hackney.ex:21: ExAws.Request.Hackney.request/5
    lib/ex_aws/request.ex:42: ExAws.Request.request_and_retry/7
    lib/ex_aws/operation/s3.ex:39: ExAws.Operation.ExAws.Operation.S3.perform/2
```

If I put the very same code elsewhere, and run with e.g. `mix run -e MyApp.my_function`, the error disappears (i.e. `HTTPoison.start()` call not needed).

Is this something which is expected?

Using Elixir 1.9.4 and Erlang 22.1.7, if it matters.

**Comment by edgurgel** [comment]
This is valid for all elixir applications. You have to call `Application.ensure_all_started(:application)` to ensure that your application is running.

A mix task will not start anything that you didn't manually start. So if your use case is using ExAws you probably want to do: `Application.ensure_all_started(:ex_aws)` inside your `run`

Phoenix points this out for example: https://hexdocs.pm/phoenix/1.4.11/phoenix_mix_tasks.html#creating-our-own-mix-tasks . The very last example of this page

**Comment by StasD** [comment]
OK, Thanks!
Only how do I figure out which application(s) to run in `Application.ensure_all_started`?
For example, you suggested to pass `:ex_aws`, but it does not actually work in my case. `:httpoison` does.
And in the example on the Phoenix page you referred to they call `Mix.Task.run("app.start")`. Which also works.

**Comment by edgurgel** [comment]
app.start is basically ensure_all_started on your main application.

if you call ensure_all_started on `:ex_aws` it will ensure that all dependencies are started then `ex_aws` is started https://hexdocs.pm/elixir/Application.html#ensure_all_started/2 . If httpoison is not a dependency of ex_aws you may have to start both

```
Application.ensure_all_started(:ex_aws)
Application.ensure_all_started(:httpoison)
```

**Comment by StasD** [comment]
I don't think ExAws has a dependency to httpoison. They say [here](https://hexdocs.pm/ex_aws/ExAws.html): 
`you'll need a compatible HTTP client (defaults to :hackney) and whatever JSON or XML codecs needed by the services you want to use`
In my `deps` function `httpoison` is explicitly specified in addition to `ex_aws` and `ex_aws_s3`.
In my case calling `ensure_all_started` with `:ex_aws` does not seem to make any difference. `:httpoison` does.
Anyway, I guess I will just use whatever make the program work. Without deep understanding of Elixir / Erlang application model, it all feels a bit of magic to me. :)
