### ISSUE TITLE
Track download progress 

### ISSUE THREAD

**Issue by smahi** [edgurgel/httpoison#403]
I am using HTTPoison to download files from the net, and would like to be able to to track the download progress.
Is it possible to track the download progress ?

**Comment by edgurgel** [comment]
No, HTTPoison does not provide progress. You can achieve that by using the content-length header and counting the data that you received so far!

**Comment by smahi** [comment]
@edgurgel Is the `content-length` gives you the length of the actual framgment your are downloading or the whole file length or it's the length of downloaded portion of the file ?
