### ISSUE TITLE
Unable to provide CA certificate data from the memory

### ISSUE THREAD

**Issue by fschuindt** [edgurgel/httpoison#405]
I'm trying to use HTTPoison to query my Kubernetes cluster REST API, for that I need to provide the "certificate authority data".

It works OK when I have the certificate in a file, using the option `:cacertfile`, like so:

```elixir
# That's the `opts` variable passed to HTTPoison.
[
  ssl: [
    cacertfile: "/path/to/my/certificate/ca.crt"
  ]
]
```

Where the `ca.crt` file looks like this:  
**(I've used a fake certificate here)**
```
-----BEGIN CERTIFICATE REQUEST-----
MIICuTCCAaECAQAwMTELMAkGA1UEBhMCQlIxEDAOBgNVBAgMB1NlcmdpcGUxEDAO
BgNVBAcMB0FyYWNhanUwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC6
S5nL05nSo1YV01H0WwkkUGXTR6Wd7tcEG4cvAvb3A1Pn0YgwjT4gflr9TLwt8NSl
wkP5LiLCm17t3vLOq9GQ5UcUe1sH7rmvfboHhzMwGdWLviVMH2+I5iY+iLulIEQ4
Of8is88oHUWaH16/opA5AdW7v3DG8jxxakRq1iXhEmB/YI2KvPqXoGw75RqGm4fv
1ZdsFtoLs8Mq44GeJLGz1V4ZC3hhq3Id4yzHSewHNe9BdtNst7D95u9oy9th/d+d
xt7IpQH9YtedBy8GUL8irMXhcEEPGFe+4bRvLdkmO3+wM3STp3rPqDyWGOC5co6e
0R9DGGAwMGC1Umgd6g5rAgMBAAGgQzBBBgkqhkiG9w0BCQ4xNDAyMA4GA1UdDwEB
/wQEAwIFoDAgBgNVHSUBAf8EFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDQYJKoZI
hvcNAQELBQADggEBAKX3px8Ox92vRh4W3SR90U6eoov+jBOI3b0T/xAFWrIyJwaM
PTRs4YyoXwFnrGIRK5KuZNu1/SVvCQBiVMoSeDeFHbUe6561LXo21eejwKpia0Oa
MyAqJVqBu30fNJUz8hWQCRgKEOzRMwhqdNMw4k51Jkt2RqnjUMRbd/V0UF3HO/5P
qpzZBjCCPmGGQsSi92bB/n/wAVx3Hc4J8iRMKKz5qNfPdU3+p5I+z5V07oc1FMpt
ZUu3ooYMnV0EXDnROIuhsrJi1WTxpF1FiKDQcGyqR1hnuHwljk4ZhFlQ6unDjaqg
pMmnjJdcYVkWSn8jU9kEUERaIHvi2KlzzkTY+oA=
-----END CERTIFICATE REQUEST-----
```

This works just fine.

But my goal is to have the certificate data in the memory, actually I'm pulling it from the database.

So I'm trying these options:

**Option 1**
```elixir
[
  ssl: [
    cert: Certificate.from_cluster(cluster)
  ]
]
```

**Option 2**
```elixir
[
  ssl: [
    cacert: Certificate.from_cluster(cluster)
  ]
]
```

That's the `Certificate` module which is being called:
```elixir
defmodule OpalAPI.Sygyzy.HTTP.Certificate do
  @moduledoc """
  Prepares the HTTP certificate of a given cluster to be used by
  HTTPoison.
  """

  alias OpalAPI.DataBase.Schemas.K8sCluster

  @doc """
  Returns the HTTPoison compatible HTTP X.509 certificate string of a
  given cluster.
  """
  @spec from_cluster(K8sCluster.t()) :: String.t()
  def from_cluster(cluster) do
    with cert <- cert_text_from(cluster) do
      cert
      |> :public_key.pem_decode()
      |> hd()
      |> elem(1)
    end
  end

  defp cert_text_from(cluster) do
    """
    -----BEGIN CERTIFICATE-----
    #{cluster.certificate}
    -----END CERTIFICATE-----
    """ |> String.trim()
  end
end
```

I have made it based on a post on this topic:  
https://elixirforum.com/t/using-client-certificates-from-a-string-with-httposion/8631/10

I have also tested the certificate output and it's fine.

That's what I get when I try the **Option 1**:
```elixir
%HTTPoison.Error{
  id: nil,
  reason: {:tls_alert,
    {:handshake_failure,
      'TLS client: In state certify at tls_connection.erl:1192 generated CLIENT ALERT: Fatal - Handshake Failure - malformed_handshake_data\n'}}
```

And for the **Option 2**:
```elixir
%HTTPoison.Error{
     id: nil,
     reason: {:options,
      {:socket_options,
       [
         cacert: "-----BEGIN CERTIFICATE-----\nMyCertificateDataHere-----\n",
         packet_size: 0,
         packet: 0,
         header: 0,
         active: false,
         mode: :binary
       ]}}
   }
```

I'm kinda lost here, don't know what to try next. :(

**Comment by edgurgel** [comment]
Hey Fernando, 

I'm sorry for the delay to reply this issue! 

HTTPoison & Hackney simply use the ssl options provided by erlang: https://erlang.org/doc/man/ssl.html

I'm not an expert on how the SSL module works but I would suggest you to simply put the cert/cacert data inside a temporary file and use the path as it's a more common use case that we know it will work? 

Otherwise probably worth asking on elixir forums or erlang-questions I think?

**Comment by edgurgel** [comment]
I'm closing this ticket as it doesn't seem to be an issue with HTTPoison. Feel free to reopen if this is not true

**Comment by fschuindt** [comment]
Having the cert in a temporary file is an odd option considering I may have multiple certificates, all of them on database on records (brought to the memory by Ecto). What I'm building is a Kubernetes cluster manager, that uses the cluster's API to manage them. Each cluster has its own certificate, so I have multiple certificates.

Would be nice to have at last an example showing how to provide the certificate from a simple string in memory, which should not be a big deal. But knowing that it is, I'll need to provide other solutions, like the temporary file you mentioned. But feels bad to know I need to write in the disk not really needing to.

I'll follow up this question on other places then.

Anyway, I'm OK in closing this, just not happy.

**Comment by edgurgel** [comment]
Again: this is not related to HTTPoison or hackney.  Most HTTP libraries won't implement SSL but simply use the Erlang library

Maybe worth talking to the Erlang dev team about a missing doc? Feel free to submit a PR to https://github.com/erlang/otp

**Comment by fschuindt** [comment]
Yes, I understand that, man. As I said:
>I'll follow up this question on other places then.

I was just expressing my feeling that's odd a HTTP lib to be "not related" to a SSL config, Tho I understand it perfectly, it's just funny and sad at the same time.

**Comment by fschuindt** [comment]
Yes, I understand that, man. As I said:
>I'll follow up this question on other places then.

I was just expressing my feeling that's odd a HTTP lib to be "not related" to a SSL config, Tho I understand it perfectly, it's just funny and sad at the same time.
