### ISSUE TITLE
HTTPoison thinks post request is a get request

### ISSUE THREAD

**Issue by 619** [edgurgel/httpoison#408]
Running 
`HTTPoison.post!("https://vision.googleapis.com/v1/images:annotate", req_body(image), headers)`

A GET request is being made. Does httpoison support POST requests?

**Comment by edgurgel** [comment]
@619 , how do you know that a GET request is being made? How I can someone replicate the issue?

**Comment by edgurgel** [comment]
You can use httpbin.org to print what a request is doing:

```
iex(3)> HTTPoison.post!("https://httpbin.org/anything", "Body").body |> IO.puts
{
  "args": {},
  "data": "Body",
  "files": {},
  "form": {},
  "headers": {
    "Content-Length": "4",
    "Content-Type": "application/octet-stream",
    "Host": "httpbin.org",
    "User-Agent": "hackney/1.15.2",
    "X-Amzn-Trace-Id": "Root=1-5ea4c633-1bd930b5f603500f998200f2"
  },
  "json": null,
  "method": "POST",
  "origin": "103.231.90.174",
  "url": "https://httpbin.org/anything"
}
```

**Comment by 619** [comment]
In all likelihood I'm using HTTPoison the wrong way. I just do not see a clear example of how to call a POST request and it doesn't seem to work when I call a POST request the same way I call a GET request (using the if case example in the README).
