### ISSUE TITLE
HTTPoison fails to send any request

### ISSUE THREAD

**Issue by r-coh** [edgurgel/httpoison#411]
When using HTTPoison request, can't figure out why, since the same works in another machine with similar specifications and settings..

```elixir
iex(33)> HTTPoison.get!("https://httpbin.org/anything")
** (HTTPoison.Error) {:options, {:sslv3, {:versions, [:"tlsv1.2", :"tlsv1.1", :tlsv1, :sslv3]}}}
    (httpoison) lib/httpoison.ex:128: HTTPoison.request!/5
```
tested this with elixir 1.9.4, OTP 23 on a centos7 machine

**Comment by r-coh** [comment]
Downgraded to otp 22 fixed it.

**Comment by inhji** [comment]
Using the following options fixed it for me:

```
[ssl: [{:versions, [:"tlsv1.2", :"tlsv1.1", :tlsv1]}]]
```

I'm on Ubuntu 18.04, OTP/23, Elixir 1.10.3 (compiled with Erlang/OTP 21)

**Comment by conradfr** [comment]
OTP23 has removed support for SSLv3 so I guess that's why we get these errors.

**Comment by inhji** [comment]
There is already a fix in hackney: https://github.com/benoitc/hackney/pull/619
It's not released yet, though.

**Comment by camstuart** [comment]
This is tricky, I'm using a dependency that in turn uses HTTPoison how can I specify:

`[ssl: [{:versions, [:"tlsv1.2", :"tlsv1.1", :tlsv1]}]]` @inhji any ideas?

**Comment by inhji** [comment]
@camstuart As far as I know, there are two ways you can get around this:

* Downgrade to OTP22. I've done this using https://github.com/asdf-vm
* Patch the library you're using to include the options for HTTPoison

Downgrading OTP seems more sensible to me, given that OTP23 is only out for less than a week at this point.

**Comment by camstuart** [comment]
I downgraded to 22, but still seem to have a problem.

**Comment by r-coh** [comment]
@camstuart you also have to rebuild your app with OTP 22

**Comment by r-coh** [comment]
`asdf` is dope; had installed, `erlang` using official yum repo, turns our centos7 has `yum-cron` which kept updating it to OTP23, wouldn't have encountered this if using `asdf`.
