### ISSUE TITLE
distinguish :timeout error

### ISSUE THREAD

**Issue by spinettaro** [edgurgel/httpoison#420]
Hi all,

do you know if there are different error for `timeout` and `recv_timeout` ?

In my case I'm using a HTTPoison.Request! and I receive a 

` ** (HTTPoison.Error) :timeout `

is this error related to first timeout ? in this case what I should see in case of `recv_timeout` ?

Thanks,
Daniele

**Comment by edgurgel** [comment]
More here: https://github.com/edgurgel/httpoison/issues/215
