### ISSUE TITLE
Unwrap responses from {:ok | :error, _} tuples

### ISSUE THREAD

**Issue by novaugust** [edgurgel/httpoison#44]
Hey there,
Would you be interested in a PR that unwraps the results of `:hackey.request` from ok/error tuples?

Keeping :ok / :error seems unnecessary when you're already wrapping the actual results in structures that can be pattern matched against to determine success/error status.

In code terms, the client API would change to something like this

```elixir
#instead of this, taken from Readme
case HTTPoison.get(url) do
  {:ok, %HTTPoison.Response{status_code: 200, body: body}} ->
    IO.puts body
  {:ok, %HTTPoison.Response{status_code: 404}} ->
    IO.puts "Not found :("
  {:error, %HTTPoison.Error{reason: reason}} ->
    IO.inspect reason
end
# This!
case HTTPoison.get(url) do
  %HTTPoison.Response{status_code: 200, body: body} ->
    IO.puts body
  %HTTPoison.Response{status_code: 404} ->
    IO.puts "Not found :("
  %HTTPoison.Error{reason: reason} ->
    IO.inspect reason
end
```

**Comment by edgurgel** [comment]
We had this discussion previously: https://github.com/edgurgel/httpoison/issues/27

It's consistent with most APIs out there and also it would break compatibility without adding much :/

**Comment by novaugust** [comment]
It would definitely be a semver bump :)
But shoot, sorry for not checking your older issues before raising this. I'll just be on my way then =)

**Comment by edgurgel** [comment]
@novaugust , sorry if I sounded like "you should have read the issues!", it was not my intention. If more people push for this change I would be glad to reconsider before turning the lib to `1.0.0`, which should not be too far...

Anyway, thank you for bringing up this discussion :)

**Comment by novaugust** [comment]
Not to worry, I was just scolding myself. You came across just fine
