### ISSUE TITLE
Request is getting closed.

### ISSUE THREAD

**Issue by navyad** [edgurgel/httpoison#445]
`https://yts.lt/api/v2/list_movies.json?query_term=tt11296058`

Above URL is always available and gives the expected output (JOSN) whicle accessing from browser

But sometimes (randomly) while access same URL using httposion, following error received:

https://yts.mx/api/v2/list_movies.json?query_term=tt11296058 
request:
`HTTPoison.get(url, [], follow_redirect: true)`

error
`{:error, %HTTPoison.Error{id: nil, reason: :closed}}`

what could be the reason here, thanks

**Comment by sreecodeslayer** [comment]
IMO, this has nothing to do with HTTPoison. Requests can be closed by remote server if its missing proper headers. A quick check suggests that the yts.lt is served through cloudflare, which can block requests or close them based on various reason specific to the host.

This probably is not the right place for such questions, and you might get better solutions on SO which are common for accessing APIs 😉

**Comment by edgurgel** [comment]
@sreecodeslayer is right. The server is closing the connection. 

If we can find a consistent way to reproduce this issue then we can investigate.
