### ISSUE TITLE
Nested form-encoded params don't work

### ISSUE THREAD

**Issue by vereis** [edgurgel/httpoison#469]
Ahoy!

We're using `HTTPoison` to interface with [Stripe's Metadata API](https://stripe.com/docs/api/metadata) and tried to do the following:

```elixir
params = %{
  "amount" => "100"
  "currency" => "usd",
  "payment_method" => card_id,
  "description" => "Invoice #{invoice.id}",
  "confirm" => true,
  "metadata" => %{"hello" => "world", "foo" => "bar"}
  }

{:ok, response} =
  HTTPoison.post( "https://api.stripe.com/v1/payment_intents", {:form, Map.to_list(params)}, [], hackney: [ basic_auth: {api_token, ""} ])
```

And we noticed that this fails with the following:

```elixir
(FunctionClauseError) no function clause matching in :hackney_bstr.to_binary/1
```

I _think_ we can fix this by changing the following

```elixir
{:form, form} -> form |> Enum.map(fn {k, v} -> "-F '#{k}=#{v}'" end) |> Enum.join(" ")
```

to:

```elixir
def deconstruct_nested_params({k, v}) when is_list(v) or is_map(v) do
  for {nested_k, nested_v} <- v do
    deconstruct_nested_params({"#{k}[#{nested_k}]", nested_v})
  end
end

def deconstruct_nested_params({k, v}) do
  {k, v}
end

...

{:form, form} -> 
  form
  |> Enum.map(&deconstruct_nested_params/1)
  |> List.flatten()
  |> Enum.map(fn {k, v} when is_-> "-F '#{k}=#{v}'" end)
  |> Enum.join(" ")
```

I know the above code is gross, but if you're happy for a contribution I'd be glad to try and clean it up & put together a PR? :heart: 

Also, do you have any thoughts about supporting maps as well as keyword lists as param keys? Since you're using `Enum` anyway, you can just say you support both which might make some dialyzer users happy.

Thanks again!

**Comment by edgurgel** [comment]
Hi @vereis ! First thanks for opening this issue!

>Also, do you have any thoughts about supporting maps as well as keyword lists as param keys? Since you're using Enum anyway, you can just say you support both which might make some dialyzer users happy.

Definitely :+1: 

In regards to the nested form-encoded params there was some discussion in the past here: https://github.com/edgurgel/httpoison/issues/121

But thinking about this again I suppose that it's harmless to accept such params given that today it simply errors out and this way of encoding nested data seems to be widely used. So please if you want send us a PR :heart: 

Thanks!

**Comment by vereis** [comment]
Oops I did search for existing issues but somehow missed that, sorry for the dupe but glad you're willing to accept a PR :heart: 

I'll submit a PR later today thank you!
