### ISSUE TITLE
multipart upload

### ISSUE THREAD

**Issue by jschoch** [edgurgel/httpoison#47]
any plans to support multipart upload?  Is this possilbe today, or do you need to use hackney_multipart somehow?

**Comment by edgurgel** [comment]
You should be able to do something like:

```
iex> IO.puts HTTPoison.post!("httpbin.org/post", {:multipart, [{"name", "value"}, {:file, "/etc/hosts"}]}).body
{
  "args": {},
  "data": "",
  "files": {
    "file": "##\n# Host Database\n#\n# localhost is used to configure the loopback interface\n# when the system is booting.  Do not change this entry.\n##\n127.0.0.1\tlocalhost\n255.255.255.255\tbroadcasthost\n::1             localhost \nfe80::1%lo0\tlocalhost\n"
  },
  "form": {
    "name": "value"
  },
  "headers": {
    "Content-Length": "616",
    "Content-Type": "multipart/form-data; boundary=---------------------------hitckzclxlucgpym",
    "Host": "httpbin.org",
    "User-Agent": "hackney/1.0.6"
  },
  "json": null,
  "origin": "210.54.34.29",
  "url": "http://httpbin.org/post"
}

```

HTTPoison will support exactly what hackney accepts as possible request body: https://github.com/benoitc/hackney#send-a-body

**Comment by jschoch** [comment]
Thanks a ton!

are you aware of a way to change the Content-Disposition name from "file" to "content", do I need to set Disposition in extraheaders or something?

**Comment by jschoch** [comment]
btw, i've tried this, but the extraheaders don't override

```elixir
options = {:multipart,[
  {:file, filename,[{"filename",filename},{"Content-Type","image/jpeg"},{"name","content"}]}
]}
```

this creates the following

```
Content-Type: multipart/form-data; boundary=---------------------------mtynipxrmpegseog
User-Agent: hackney/1.0.6
Host: localhost:9010
Content-Length: 291

-----------------------------mtynipxrmpegseog
content-length: 48
content-disposition: form-data; name=file; filename="test.txt"
filename: test.txt
content-type: image/jpeg
name: content

```

I need name=file to be name=content, but i'm not sure how to get that form element set correctly in conjunction with :file

**Comment by jschoch** [comment]
ok, i've been able to get the request the way I want it via hackney directly, but the amazon cloud drive api isn't liking the request

```elixir
    url = "http://localhost:9010/foo"
    filename = "test.txt"
    header = ["Authorization": "Bearer #{@at}"]
    options = {:multipart, [
        {:file, filename, {"form-data",
          [{"name", "content"}, {"filename", filename}]},
          [{"Content-Type", "image/jpeg"}]
        },
        {"metadata", ~s({"name":#{filename},"kind":"FILE"})}
      ]}
    res = :hackney.post(url, header, options)

**Comment by edgurgel** [comment]
I wonder if you are hitting this issue: https://github.com/benoitc/hackney/issues/171

**Comment by jschoch** [comment]
This was an issue with the api endpoint I was using.  closing the issue.

**Comment by edgurgel** [comment]
Oh! Great! I will probably add a test to have an "example" there for multipart upload.

**Comment by edgurgel** [comment]
Done by https://github.com/edgurgel/httpoison/commit/af3931f9c00f4d520697243fbac4c1d7125418ee
