### ISSUE TITLE
"Path not supported by Algolia REST API"

### ISSUE THREAD

**Issue by inactgrid** [edgurgel/httpoison#471]
I'm encountering the same problem as in #116 issue from 2016.
Possibly the asterisk in the url is causing it. It could be [issue with Hackney](https://github.com/benoitc/hackney/issues/272).
I tried looking at the code but I'm not competent enough to troubleshoot it.

The issue:
- `$ curl 'https://m19dxw5x0q-dsn.algolia.net/1/indexes/*/queries' --data-raw ''` returns "400, no content in POST request", as expected
- `HTTPoison.post! "https://m19dxw5x0q-3.algolianet.com/1/indexes/*/queries", ""` returns "404, path not supported by Algolia REST API", despite it being a valid path

Proper instructions to reproduce:
- Open the [network](https://curlconverter.com/images/chrome.webp) tab in the DevTools
- Go to [`https://fontawesome.com/search?q=poison`](https://fontawesome.com/search?q=poison) (or try [other websites using Algolia](https://www.wappalyzer.com/technologies/search-engines/algolia/))
- Copy the XHR request as cURL, executing it in shell will return search results, as expected
- Convert the same cURL to HTTPoison with https://curlconverter.com/elixir/, executing it will return 404

**Comment by kyleboe** [comment]
It is actually a bug in the url spec implementation by hackney. I fixed it here: https://github.com/benoitc/hackney/pull/720

**Comment by kyleboe** [comment]
The fix was merged into hackney `1.20.0` https://github.com/benoitc/hackney/pull/720
