### ISSUE TITLE
Receiving connect_timeout on specific url

### ISSUE THREAD

**Issue by jonhkr** [edgurgel/httpoison#49]
Hello everyone,

I'm trying to do a request on this url `https://qasecommerce.cielo.com.br/servicos/ecommwsec.do` but I'm receiving this error `{:error, :connect_timeout}`.
I think it is something related to `SSL` and `TSLv1`, does anybody know if it is and erlang issue and how to fix it?

Doing the request with `curl` works fine.

Thank you.

**Comment by edgurgel** [comment]
hey @jonhkr, could you specify which HTTPoison version you are using and also hackney's version ?

Thanks

**Comment by jonhkr** [comment]
Hi @edgurgel,
I figured out the problem was indeed with `TLSv1`, I had to force the `:ssl_options` option to make it to work.
The following is the working snippet:
```Elixir
url = "https://qasecommerce.cielo.com.br/servicos/ecommwsec.do"
options = [hackney: [ssl_options: [versions: [:tlsv1]]]]
HTTPoison.post(url, {:form, data: d}, [], options)
```
Thank you.
