### ISSUE TITLE
Stubbing HTTPoison responses

### ISSUE THREAD

**Issue by kkirsche** [edgurgel/httpoison#50]
Hey guys,

I'm new to using HTTPoison, but I had a quick question. I'm looking to build a simple API wrapper with HTTPoison as I learn more about how to use it. How would I stub HTTPoison's requests (GET/POST/etc.) so that I can control the test results while still ensuring the proper URL, etc. are being received.

Any best practices about stubbing responses would be helpful. Thanks!

**Comment by edgurgel** [comment]
You can use [exvcr](https://github.com/parroty/exvcr) or simply https://github.com/eproxus/meck and stub HTTPoison requests. I use meck on some tests to stub `hackney`, for example: https://github.com/edgurgel/httpoison/blob/master/test/httpoison_base_test.exs#L44-L55
