### ISSUE TITLE
HTTPoison.start required if I have multiple clients?

### ISSUE THREAD

**Issue by jeregrine** [edgurgel/httpoison#52]
Since HTTPoison.Base just checks that the application is started https://github.com/edgurgel/httpoison/blob/master/lib/httpoison/base.ex#L80 is it absolutely required for each HTTPPoison.Base that I have in the project? Or can I just call `:application.ensure_all_started(:httpoison)` once?

**Comment by edgurgel** [comment]
The HTTPoison.start is just a helper for people to use dynamically, for example on some script or on iex. You can simply add `:httpoison` to your mix.exs on `applications` and you will be fine to use HTTPoison anywhere.
