### ISSUE TITLE
Segmentation fault when executing POST

### ISSUE THREAD

**Issue by apotry** [edgurgel/httpoison#53]
The following works (I know this is not the correct way to call this API but it serves as a working example):

    HTTPoison.request(:post, "https://api.github.com", "asdf", [{"Accept", "application/json"}])

But if I do 

    HTTPoison.request(:post, "https://identitysso.betfair.com/api/login", "asdf", [{"Accept", "application/json"}])

then iex crashes with a segmentation fault every time.

**Comment by apotry** [comment]
Ok, fixed it - this must have been an issue with the combination of homebrew, erlang, elixir and openssl. After running

    brew install erlang --build-from-source
    brew install elixir --build-from-source

the segmentation fault is gone.

**Comment by edgurgel** [comment]
Great!
