### ISSUE TITLE
Timeout not working?

### ISSUE THREAD

**Issue by jordi-chacon** [edgurgel/httpoison#54]
Hi,

I am running a simple Cowboy server with a tiny Plug that simply sleeps for 3 seconds.

I then send a GET request through HTTPoison, with a timeout of 1ms, yet the connection doesn't timeout.

Here is the gist:
https://gist.github.com/jordi-chacon/871ab45df432e0668740

Do you know why this is happening?

Thanks a lot!

**Comment by edgurgel** [comment]
It works but this feature didn't get released. I'm planning to release a new version soon. 

For now you can do

```
HTTPoison.get("http://localhost:4000", [], hackney: [recv_timeout: 1])
```

When I release this out we can close this issue.

**Comment by jordi-chacon** [comment]
Thank you very much, that worked like a charm!

**Comment by edgurgel** [comment]
It should be available if you use 0.7.0 that just got released

**Comment by uri** [comment]
Is setting `hackney: [recv_timeout: 1]` the same as setting `timeout: 1`?

**Comment by Dzol** [comment]
> Is setting hackney: [recv_timeout: 1] the same as setting timeout: 1?

I'm wondering @uri's question too 🙂
