### ISSUE TITLE
Synchronous response truncated

### ISSUE THREAD

**Issue by dmilith** [edgurgel/httpoison#61]
I'm trying to fetch synchronously a 8MiB text file - http://www.unsubscore.com/blacklist.txt
I can't make Httpoison to complete the request, it ends on random spots and content is truncated.

**Comment by dmilith** [comment]
Doing things asynchronously helps, but synchronous call is what I'm looking for.

**Comment by edgurgel** [comment]
I'm having no problem to download this data through sync `HTTPoison.get!`. I imagine the server is closing the connection while hackney is fetching the body. 

Async and sync requests do not fetch the body the exact same way and the server may misbehave with one or another. I will try to reproduce this and find a solution. Thanks for the report. I would suggest to use the `async` request and receive body chunks for now.

**Comment by edgurgel** [comment]
We can reopen if we get more information or a way to reproduce.
