### ISSUE TITLE
Unknown CA error with HTTPoison 0.7

### ISSUE THREAD

**Issue by jakubpawlowicz** [edgurgel/httpoison#62]
```elixir
iex(1)> HTTPoison.get("https://app.promoter.io")
[error] SSL: :certify: ssl_handshake.erl:1401:Fatal error: unknown ca

{:error, %HTTPoison.Error{id: nil, reason: {:tls_alert, 'unknown ca'}}}
```

Tested on Erlang 17.5 and 18, with the same effect. Works fine in HTTPotion, though.

**Comment by edgurgel** [comment]
It's probably related to this issue here: https://github.com/benoitc/hackney/issues/215

**Comment by jakubpawlowicz** [comment]
Yeah, that could be it. I wonder what's the resolution going to be.

**Comment by edgurgel** [comment]
@jakubpawlowicz could you try overriding hackney dependency to:

      `{:hackney, github: "benoitc/hackney", tag: "1.3.0"},`

**Comment by jakubpawlowicz** [comment]
:+1: that works now, except I had to override it:

```elixir
{:hackney, github: "benoitc/hackney", tag: "1.3.0", override: true}
```

**Comment by edgurgel** [comment]
Great! As soon as the hackney 1.3.0 gets released I will update HTTPoison and release a new minor version.

**Comment by DavsX** [comment]
Just a heads up (don't know if I should open an issue for this or not): using proxy with hackney 1.2.0 is not working as it does not export the hackney_connect.ssl_opts/2 function. It is fixed in 1.3.0, so the solution described by @jakubpawlowicz should be used.

**Comment by edgurgel** [comment]
HTTPoison 0.7.1 will require ~> 1.3.0 hackney https://github.com/edgurgel/httpoison/releases/tag/v0.7.1

Thanks again, guys!

**Comment by jakubpawlowicz** [comment]
Thank you!
