### ISSUE TITLE
The unlimited recv_timout causes HTTPoison to eventually stop working

### ISSUE THREAD

**Issue by mschae** [edgurgel/httpoison#64]
Hey @edgurgel,

First off let me thank you for this awesome library, which has become my go-to everywhere I use Elixir (which is everywhere).

However we noticed this problem in ex_aws before and I have it across different apps in which I use HTTPoison:
After running for a long while (say a week) any HTTPoison requests just stop working. They don't fail, they don't time out, they simply never execute, stalling the entire process with them.

What we believe is happening is that the `:infinity`, that's the default in hackney for `recv_timeout` causes each worker in the pool (I believe it's 50 in the default config) to wait for an ack. It happens rarely that they don't receive the ack but it happens and which a high enough n eventually every worker is waiting and the pool exhausted. Now I could pass a different `recv_timeout` in each `HTTPoison.get` call but that would be bothersome and I am lazy.

Any chance we can change the default here? For example by using a application configuration option?

Thanks,
Michael

**Comment by mschae** [comment]
To add a bit of credibility to my assumption:

I created a simple plug that just executes a `:timer.sleep :infinity`. I then used `Task.async` to do 100 `HTTPoison.get`s to that enpoint.

The result is that I see 100 processes executing HTTPoison.get that are all stalled. Executing more `HTTPoison.get`s just results in a stalled process. That's exactly what we were seeing.

I hope that makes sense.

**Comment by edgurgel** [comment]
There's an issue on hackney about this https://github.com/benoitc/hackney/issues/219. Let's see what it will be decided there and we go forward. I think it's a fair change to be applied.

Thanks for such a complete explanation :+1:

**Comment by RJ** [comment]
@mschae if you manually set recv_timeout does it avoid the hanging problem? I've seen a similar issue, set the timeouts*, but still see the stalling of subsequent requests (never clears, have to restart hackney app to kill them all)
wondering if i need to set some other timeout too.

* https://github.com/irccloud/mini_s3/commit/d246fd259ebf2377d4b5dd4770f759ba2bc941c5

**Comment by mschae** [comment]
@RJ we first found this here: hexpm/hex_web#133 (we moved away from mini_s3 btw). 

From what I can tell adding the recv_timeout fixed the hanging problem but maybe @benwilson512 and @ericmj can confirm that.

Thanks for pointing out that discussion on hackney @edgurgel, definitely aboard with waiting to see what their solution will be.

**Comment by benwilson512** [comment]
Manually setting the recv_timeout fixed it as far as I know.

**Comment by edgurgel** [comment]
As soon as hackney 1.3.1 is on hex.pm, a simple mix update on httpoison will grab it.

**Comment by edgurgel** [comment]
https://github.com/benoitc/hackney/releases/tag/1.3.1

**Comment by mschae** [comment]
I consider this closed then. Thanks @edgurgel !

**Comment by obmarg** [comment]
I am not sure that hackney 1.3.1 fixes this.  Hackney 1.3.1 specifies it's own default timeout, but HTTPoison still looks like it's defaulting to infinity: https://github.com/edgurgel/httpoison/blob/50bf08da0b8591c392dc42c3efd5e62c62582c3b/lib/httpoison/base.ex#L178

**Comment by mschae** [comment]
Right you are! I forgot HTTPoison is setting its own `recv_timeout`.

**Comment by edgurgel** [comment]
Yes! Should we pass `recv_timeout` only if passed by the user? So we would stick with whatever hackney decided as default. Does it make sense?

**Comment by mschae** [comment]
It does! Let's do that.

**Comment by edgurgel** [comment]
Cool I added this change https://github.com/edgurgel/httpoison/commit/bd6d601c38aa5570d633f4eada6a94c1e051a8b7 and as soon as 1.3.1 gets published to hex (https://github.com/hexpm/community/pull/61) I will bump the requirement and release a new version. I will close the issue when everything is done :)

**Comment by mschae** [comment]
1.3.1 was published! Awesome! Thanks again @edgurgel

**Comment by edgurgel** [comment]
Sweet I will published later today a new version. Thanks, folks!

**Comment by edgurgel** [comment]
https://github.com/edgurgel/httpoison/releases/tag/v0.7.2 

A simple `mix deps.update httpoison` should do the job!
