### ISSUE TITLE
undefined function: Dict.slice/2 in "Wrapping HTTPoison.Base" example code

### ISSUE THREAD

**Issue by goofansu** [edgurgel/httpoison#66]
Elixir version: 1.0.5

There  is no `Dict.slice` in Elixir.

**Comment by edgurgel** [comment]
Oops! This was recently introduce by https://github.com/edgurgel/httpoison/pull/65

I should have tested xD

**Comment by edgurgel** [comment]
Fixed by https://github.com/edgurgel/httpoison/commit/c1ea5fbd14c8101a167f43500aa1941cb774d10c
It's not as idiomatic as I would like to be, but it's working now :)

**Comment by goofansu** [comment]
Nice, thanks

**Comment by edgurgel** [comment]
Thanks for warning about it :+1:

**Comment by goofansu** [comment]
@edgurgel , "Dict.take(@expected_fields)" seems not necessary.

If the key is not in `@expected_fields`, it will throw `argument error` when executing `String.to_existing_atom(key)`.

**Comment by edgurgel** [comment]
Yeah, we would probably need to `Dict.take` the expected fields as strings then do the `to_existing_atom` :(
