### ISSUE TITLE
Looking up a specific header in a response

### ISSUE THREAD

**Issue by lpil** [edgurgel/httpoison#70]
Hello!

Currently it seems that HTTPoison's responses' headers are a list of pairs of strings, like this:

```elixir
[
  {"foo", "one"},
  {"bar", "two"},
]
```

Unless I'm missing something this makes it awkward to look up a specific header (I'm interested in the content type), as I have to iterate over each element of the list until I find the one I want, say with `Enum.find_value/2`.

I feel like I want headers to be a Dict of some type, so I can use `foo["bar"]`.

Is there a better way to do this out of the box?

Thanks,
Louis

**Comment by edgurgel** [comment]
They were maps before and there's a good reason why they are now lists: https://github.com/edgurgel/httpoison/pull/45

You can `use HTTPoison.Base` and override `process_headers` using `Enum.into`

`defp process_headers(headers), do: Enum.into(headers, %{})`

This way your response headers will show up as maps.

You can also possibly just use [List.keyfind/4](http://elixir-lang.org/docs/v1.0/elixir/List.html#keyfind/4).

P.S.: Elixir had a `ListDict` but it was removed: https://groups.google.com/forum/#!topic/elixir-lang-core/0LUpo1YIoTQ

**Comment by lpil** [comment]
Ah, I didn't know it was possible to have the same header twice.

Thank you for your help. :)

Ping @jonnyarnold, `List.keyfind/4` looks like a much nicer solution than what we did.

**Comment by edgurgel** [comment]
:+1:
