### ISSUE TITLE
Async request to streaming server - How to keep alive or extend connection timeout?

### ISSUE THREAD

**Issue by amokan** [edgurgel/httpoison#72]
I am trying to access a third-party streaming api ( _[the flowdock api](https://www.flowdock.com/api/streaming) to be exact_ ) and expected I could make a request and just handle the `AsyncChunk` messages as they roll in. The api sends periodic _keep-alive_ responses, apparently, but I'm not getting that far due to timeouts.

I was able to put something real crude together and everything is ok as long as I keep causing chunks to come in (_by creating messages in Flowdock_). However, if I let things go idle for about five seconds - I end up with a `%HTTPoison.Error{id: #Reference<0.0.2.15>, reason: {:closed, :timeout}}`.

```
defmodule FlowdockTest do
  use GenServer

  def start_link(opts \\ []) do
    GenServer.start_link(__MODULE__, :ok, opts)
  end

  def init(:ok) do
    url = "https://foo:bar@stream.flowdock.com/flows/foo/bar"
    {:ok, HTTPoison.get!(url, %{"Accept" => "application/json"}, [stream_to: self])}
  end

  def handle_info(msg, state) do
    IO.inspect {:handle_info, msg}
    {:noreply, state}
  end

end
```

Am I doing something terribly wrong here or is this not a good approach for accessing a streaming api? I know the code example is simple and less than ideal, but it feels like I'm missing an option or something to force HTTPoison or Hackney to keep the connection open.

**Comment by ashneyderman** [comment]
did you try to add recv_timeout option as infinity like so -
  [recv_timeout: :infinity]
?

**Comment by amokan** [comment]
@ashneyderman Did not try that or see it documented. Will give it a go.

**Comment by edgurgel** [comment]
Thanks @ashneyderman . Yeah you are probably reaching the `recv_timeout`. We should document what this timeout affects on the request lifetime. Thanks for reporting the issue.

**Comment by amokan** [comment]
@ashneyderman @edgurgel yeah, this works now with the `[recv_timeout: :infinity]` - Thanks guys!

**Comment by edgurgel** [comment]
I just added more information to the docs for the `request/5` function: https://github.com/edgurgel/httpoison/blob/master/lib/httpoison/base.ex#L124-L133

It should be clear now! Cheers!
