### ISSUE TITLE
Load balancing and workers

### ISSUE THREAD

**Issue by sebyx07** [edgurgel/httpoison#73]
Is there a way or **need** to load balance requests through a supervisor-worker tree ?

I have several modules that use HTTPoison.Base

**Comment by edgurgel** [comment]
Hackney uses a default pool of connections and reuse it (if it's a request for the same host). If you want to, you can use different pools for different purposes so they don't interact with the same resources.

More info: https://github.com/benoitc/hackney#use-the-default-pool

You could  add the pools to your supervisor using the provided `child_spec` https://github.com/benoitc/hackney/blob/master/src/hackney_connect/hackney_pool.erl#L140-L143 and for each module you use HTTPoison you could pass the pool to be used as a hackney option.

Does this make sense?

**Comment by edgurgel** [comment]
Does this answer your question, @sebyx07 ? I can try to write an example if more info is needed :)

**Comment by sebyx07** [comment]
yes, that would be awesome :+1:

**Comment by edgurgel** [comment]
Right now you can simply run:

```
HTTPoison.get("httpbin.org/get", [], hackney: [pool: :first_pool])
HTTPoison.get("httpbin.org/get", [], hackney: [pool: :second_pool])
```

Hackney will create a pool with the passed name if it doesn't exist. They won't compete for the same resources.

If you want to use different default options you can start them when your app starts (more here: http://elixir-lang.org/getting-started/mix-otp/supervisor-and-application.html#the-application-callback) using `:hackney_pool.start_pool/2`.

```
:ok = :hackney_pool.start_pool(:first_pool, [timeout: 15000, max_connections: 100])
```
From hackney README:


>timeout is the time we keep the connection alive in the pool, max_connections is the number of connections maintained in the pool. Each connection in a pool is monitored and closed connections are removed automatically.

The third option is to add the pool as part of your supervision tree

```
    children = [
      :hackney_pool.child_spec(:first_pool,  [timeout: 15000, max_connections: 100])
    ]
```

And then `first_pool` will be available to be used by HTTPoison/hackney

More about supervision trees:  http://elixir-lang.org/getting-started/mix-otp/supervisor-and-application.html#supervision-trees

**Comment by sebyx07** [comment]
good job :jack_o_lantern:

**Comment by tompave** [comment]
This is _very_ useful information. How do you feel about adding it to the Readme?

**Comment by killme2008** [comment]
@edgurgel

Hi, maybe you can add this information to README. It's useful for users.

**Comment by edgurgel** [comment]
PRs are welcomed 👍

**Comment by tompave** [comment]
Right.
https://github.com/edgurgel/httpoison/pull/199

**Comment by edgurgel** [comment]
Awesome! thanks! :)
