### ISSUE TITLE
httpoison should not define large chunk of code in my modules

### ISSUE THREAD

**Issue by josevalim** [edgurgel/httpoison#75]
Although I don't agree with the `Base` approach in httpoison, the minimum that could be done is to at least keep the function definitions short. For example, instead of:

```elixir
      def transformer(target) do
        receive do
          {:hackney_response, id, {:status, code, _reason}} ->
            send target, %HTTPoison.AsyncStatus{id: id, code: process_status_code(code)}
            transformer(target)
          {:hackney_response, id, {:headers, headers}} ->
            send target, %HTTPoison.AsyncHeaders{id: id, headers: process_headers(headers)}
            transformer(target)
          {:hackney_response, id, :done} ->
            send target, %HTTPoison.AsyncEnd{id: id}
          {:hackney_response, id, {:error, reason}} ->
            send target, %HTTPoison.Error{id: id, reason: reason}
          {:hackney_response, id, chunk} ->
            send target, %HTTPoison.AsyncChunk{id: id, chunk: process_response_chunk(chunk)}
            transformer(target)
        end
      end
```

httpoison should inject:

```elixir
def transformer(target) do
  HTTPoison.Base.transformer(__MODULE__, target)
end
```

**Comment by edgurgel** [comment]
I **completely** agree with both points. My initial implementation was mostly a clone of HTTPotion and I included the same approach of adding these functions inside the module. I'm not a fan of them and I'm trying to find a good replacement for this approach with another library ([not published yet](https://github.com/edgurgel/httpehaviour)).

I will move the transformer function out of the "included" functions. 

Thanks for the report!
