### ISSUE TITLE
Allow setting hackney pool size 

### ISSUE THREAD

**Issue by shankardevy** [edgurgel/httpoison#85]
I don't see how I could change the pool size of hackney from default 50 max_connections.

**Comment by edgurgel** [comment]
I think you can simply change hackney's application env or use your own pool (More info here: https://github.com/edgurgel/httpoison/issues/73)

```
iex(1)> Application.get_all_env(:hackney)
[shutdown: 10000, restart: :permanent, max_connections: 50, timeout: 150000,
 maxr: 10, included_applications: [:ssl_verify_hostname], maxt: 1]
```
