### ISSUE TITLE
Timeouts when making POST requests

### ISSUE THREAD

**Issue by HashNuke** [edgurgel/httpoison#86]
Hound uses HTTPoison under the covers to make requests to the WebDriver JSON API.

Making a POST request to the chrome driver fails. Here are steps to reproduce.

### Requirements

* Install chromedriver from homebrew if Mac (`brew install chromedriver`) or download from http://chromedriver.storage.googleapis.com/index.html?path=2.20/

* Start the chrome driver with `chromedriver --verbose`

### Reproducing the error

```
body = Poison.encode! %{desiredCapabilities: %{}}
headers = [{"Content-Type", "text/json"}]
url = "http://localhost:9515/session"
HTTPoison.post(url, body, headers)
```
The request times out after a long time. Should be useful to pass the [recv_timeout: 5000] option to debug faster.

The same request is successful with a response when using curl in the command line:
```
$ curl --data "{\"desiredCapabilities\": {}}" --header "Content-type: text/json" http://localhost:9515/session
{"sessionId":"87d6b9cfb5bd2bd1782e65f2b6a30511","status":0,"value":{"acceptSslCerts":true,"applicationCacheEnabled":false,"browserConnectionEnabled":false,"browserName":"chrome","chrome":{"userDataDir":"/var/folders/96/1sp35x9j2n116stp3gtk3m5w0000gn/T/.org.chromium.Chromium.MBiD8D"},"cssSelectorsEnabled":true,"databaseEnabled":false,"handlesAlerts":true,"hasTouchScreen":false,"javascriptEnabled":true,"locationContextEnabled":true,"mobileEmulationEnabled":false,"nativeEvents":true,"platform":"Mac OS X","rotatable":false,"takesHeapSnapshot":true,"takesScreenshot":true,"version":"46.0.2490.80","webStorageEnabled":true}}
```
Please do let me know if I'm doing something wrong.

**Comment by HashNuke** [comment]
Update: I just found out that the problem is with hackney itself.

Here's a snippet to tryout:

```
body = Poison.encode! %{desiredCapabilities: %{}}
headers = [{"Content-Type", "text/json"}]
method = :get
url = "http://localhost:9515/session"

{:ok, sc, rh, cr} = :hackney.request(:get, url, headers, body)
{:ok, body} = :hackney.body(cr)
```

If I'm doing it right, then the issue is with hackney fetching the response.

**Comment by HashNuke** [comment]
@edgurgel Since this is a hackney issue, I've started an issue on the hackney repo instead. Closing this since it's duplicate.

**Comment by HashNuke** [comment]
Mistake in my hackney example. It's a `post` request. 

```
body = Poison.encode! %{desiredCapabilities: %{}}
headers = [{"Content-Type", "text/json"}]
method = :get
url = "http://localhost:9515/session"

{:ok, sc, rh, cr} = :hackney.request(:post, url, headers, body)
{:ok, body} = :hackney.body(cr)
```

and now it works. So this looks like it's a httpoison problem. Reopening this issue.

**Comment by benoitc** [comment]
@HashNuke there was an issue with the url above, the chromedriver is sending incorrect headers. Since it isn't alone, i fixed this case with the following change:

 benoitc/hackney#6f16c1ee114c92fa1d47c3d4379c0379a91509c8  

[Test pass](https://travis-ci.org/benoitc/hackney). I will make a new release later tonight.

**Comment by HashNuke** [comment]
@benoitc thanks a lot for the fix ~! Just looked at the commit, Didn't know that the space mattered in headers.

**Comment by edgurgel** [comment]
Thanks @benoitc and @HashNuke! I'm glad you guys found this issue and fixed it! I think it's a good reason to bump hackney's version on HTTPoison. :tada:
