### ISSUE TITLE
HTTPoison / Hackney Crash

### ISSUE THREAD

**Issue by mmport80** [edgurgel/httpoison#87]
I just ran into something - any pointers n where to go next would be great - just started with Elixir etc.

When I run this:

HTTPoison.get("http://tmblr.co/Zjsg5q1x9XOT4", [], [ hackney: hackney ])

I see this:

** (MatchError) no match of right hand side value: {:error, {:closed, ""}}
      (hackney) src/hackney_client/hackney.erl:796: :hackney.redirect/2
      (hackney) src/hackney_client/hackney.erl:761: :hackney.maybe_redirect1/3
      (hackney) src/hackney_client/hackney.erl:367: :hackney.send_request/2
      (hackney) src/hackney_client/hackney.erl:832: :hackney.redirect/2
      (hackney) src/hackney_client/hackney.erl:761: :hackney.maybe_redirect1/3
      (hackney) src/hackney_client/hackney.erl:367: :hackney.send_request/2
    (httpoison) lib/httpoison/base.ex:375: HTTPoison.Base.request/9

**Comment by edgurgel** [comment]
Can you share what `hackney` holds as a variable?

**Comment by mmport80** [comment]
Oh - forgot - here you go:

hackney = [follow_redirect: true]

**Comment by mmport80** [comment]
OK, found another problem. Hmmm.

expanded_url = "http://www.rug.nl/research/ggdc/data/pwt/"
HTTPoison.get(expanded_url, [], [ hackney: hackney ])

** (ArgumentError) argument error
                :erlang.list_to_integer('      37043')
      (hackney) src/hackney_client/hackney_response.erl:104: :hackney_response.wait_headers/4
      (hackney) src/hackney_client/hackney.erl:361: :hackney.send_request/2
    (httpoison) lib/httpoison/base.ex:375: HTTPoison.Base.request/9

**Comment by edgurgel** [comment]
Could you please try again updating HTTPoison to 0.8.0 ?

**Comment by mmport80** [comment]
yup will do so now and let you know - thanks!

**Comment by mmport80** [comment]
OK... I updated, and I am still getting the same error with Tumblr URLs for some odd reason. e.g.

HTTPoison.get("https://t.co/JpP73chYaQ", [], [ hackney: [follow_redirect: true] ])

Let me know if there's any more info you need...

**Comment by eidge** [comment]
Having the same exact problem on 0.8.0 using:

```
HTTPoison.get('http://google.pt/', [], ["params": %{"asd": "2"}])
```
throws 

```
** (ArgumentError) argument error
    (httpoison) lib/httpoison.ex:66: HTTPoison.request/5
```

**Comment by edgurgel** [comment]
@eidge it's a different argument error. Try with double quotes. Double quotes and single quotes are different things in Elixir
`HTTPoison.get("http://google.pt/", [], ["params": %{"asd": "2"}])`

**Comment by eidge** [comment]
@edgurgel oh yes you're right! Still trying to get the ruby out of my muscle memory...

Thanks! :)

**Comment by edgurgel** [comment]
I couldn't replicate any more. Closing for now. Feel free to reopen if it's still an issue!
