### ISSUE TITLE
named file upload

### ISSUE THREAD

**Issue by Zensavona** [edgurgel/httpoison#89]
Hey :)

Just wondering what the correct way to POST a file with a named key is, for example the following code sends the file as the filename, where I would like to specify the parameter name it's sent as:

```
file = "file.jpg"
HTTPoison.post!(url, {:multipart, [{"device_timestamp", timestamp}, {:file, file}]}, headers, options)
```

Is it possible to send the `:file` with a name like "photo"? When I proxy the request I can see now it's named "file.jpg"

Thanks!

EDIT: actually I just inspected the raw request and I can see
```
content-disposition: form-data; name=file; filename="file.jpg"
```

**Comment by Zensavona** [comment]
A nice guy on the Elixir Slack helped me figure this one out :)

http://stackoverflow.com/questions/33557133/http-post-multipart-with-named-file/33564328#33564328

**Comment by edgurgel** [comment]
This seems like a nice example to add to the docs somehow...
