### ISSUE TITLE
Why does a 404 status code return :ok?

### ISSUE THREAD

**Issue by ianwalter** [edgurgel/httpoison#91]
What's the rational behind returning the status as `:ok` instead of `:error`? It seems counterintuitive to me. Thanks!

**Comment by edgurgel** [comment]
Hi @ianwalter, the `:ok` tuple means: this request didn't fail (connection was not closed, it reached the server, the whole request was transmitted, etc). 

The status code is dependent on the application. It may seem clear that 404 is an error, but what about a 303 or a 301? Should they be `error` or `ok`?

You may even have APIs that always return 200 and putting some error status inside the JSON payload. For example:

```
$ curl -i "http://api.openweathermap.org/data/2.5/weather?id=21372797&appid=2de143494c0b295cca9337e1e96b00e0"
HTTP/1.1 200 OK
Server: nginx
Date: Sun, 08 Nov 2015 05:32:04 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
X-Source: redis
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
Access-Control-Allow-Methods: GET, POST

{"cod":"404","message":"Error: Not found city"}
```

**Comment by LucianoGraziani** [comment]
> HTTP/1.1 200 OK

That 200 is extrange. Why don't send a 404 error? With that `200 OK` response, you have to handle errors in the *success* function.

What actually I have to do:

```js
import axios from 'axios';

const OPEN_WEATHER_MAP_URL = 'http://api.openweathermap.org/data/2.5/weather?appid=XXXXXXXXXXXXX&units=metric';

export default {
  getTemp : function getTemp(location) {
    var encodedLocation = encodeURIComponent(location),
    requestUrl = `${OPEN_WEATHER_MAP_URL}&q=${encodedLocation}`;

    return axios.get(requestUrl).then(function success(res) {
      // I have to check inside the success function
      if (res.data.cod && res.data.message) {
        throw new Error(res.data.message);
      }
      return res.data.main.temp;
    }, function error(res) {
      throw new Error(res.data.message);
    });
  },
};
```

What could be better:

```js
import axios from 'axios';

const OPEN_WEATHER_MAP_URL = 'http://api.openweathermap.org/data/2.5/weather?appid=XXXXXXXXXXXXX&units=metric';

export default {
  getTemp : function getTemp(location) {
    var encodedLocation = encodeURIComponent(location),
    requestUrl = `${OPEN_WEATHER_MAP_URL}&q=${encodedLocation}`;

    return axios.get(requestUrl).then(function success(res) {
      return res.data.main.temp;
    }, function error(res) {
      // Since the header HTTP response is 404, it fails
      throw new Error(res.data.message);
    });
  },
};
```

It can be possible to you to have a "standard" http header for errors like that? Errors who are not related a malfunction.

Thanks!

**Comment by edgurgel** [comment]
The open weather API is simply wrong. You should not reply 200 when the requested resource doesn't exist. I can't see how the client (HTTPoison) can protect anyone from such broken API.
