### ISSUE TITLE
Make the body of a POST request optional

### ISSUE THREAD

**Issue by ianwalter** [edgurgel/httpoison#92]
Would a PR that makes the body of a HTTPoison.post call optional be acceptable? I think this would make the library more flexible. My particular use case is for interacting with ElasticSearch's Search API. Thank you.

**Comment by edgurgel** [comment]
Correct me if I'm wrong but I suspect that most of the time your request to the search API will have a body as Elasticsearch uses the JSON payload to query. If I remember well you can also do a GET when interacting with the Search API if you don't have a body to send.

This doesn't seem like a great change to make as it will potentially break calls to `post/5` where people do not pass headers, body, options arguments.

**Comment by ianwalter** [comment]
Most of the time maybe, but having an empty query is still a valid use case (i.e. returning all documents of a certain type). Switching between GET and POST depending on the query is unnecessarily complex. 
I initially thought sending an empty JSON object was messing up the query, but it turns out that my index needed to be refreshed. So not a big deal, I can just send an empty object. Thank you.
