### ISSUE TITLE
Support streaming requests and responses

### ISSUE THREAD

**Issue by edevil** [edgurgel/httpoison#97]
According to the Hackney documentation we can stream a response by passing {:async, :once} and then fetch the remaining chunks by calling stream_next/1 but I can't find this function in HTTPoison. I don't want to use stream_to because I want to throttle the data.

I haven't yet gotten to the streaming request part, is it supported? I didn't find any reference to send_body.

**Comment by edgurgel** [comment]
HTTPoison has no support for these but it would be a nice addition to the library. We would need to find an interesting interface that plays nicely with the rest of HTTPoison.

**Comment by mkarnebeek** [comment]
I've encountered the same issue, and had a discussion with Elixir developers about it at https://elixirforum.com/t/streaming-http-response-without-running-out-of-memory/1887/2.

**Comment by edgurgel** [comment]
Related: https://github.com/edgurgel/httpoison/issues/103

**Comment by edgurgel** [comment]
Closing this an focusing the attention on #103
